
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2a7a165461fd33ea91b3ccdb3fad93dc5bb6fbf4",
 "version": "1.4.0.pre0.post.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
