
#ImportModules
import ShareYourSystem as SYS


#Define
MyDrawer=SYS.DrawerClass(
	).draw(
		{
			'|fig1':{
				'-Panels':{
					'|A':{
						'-Axes':{
							'|a':{
								'-Plots':{
										'|0':{
											'FiguringDrawVariable':
											[
												(
													'#plot',
													{
														'#liarg':[
															[1,2,3],
															[2,6,3]
														],
														'#kwarg':{
															'linestyle':"",
															'marker':'o'
														}
													}
												)
											]
										},
										'|1':{
											'FiguringDrawVariable':
											[
												(
													'#plot',
													{
														'#liarg':[
															[0,1,2],
															[2,3,4]
														],
														'#kwarg':{
															'linestyle':"--",
															'color':'r'
														}
													}
												)
											],
										}
									}
							},
							'|b':{
								'FiguringDrawVariable':
								[
									(
										'#plot',
										{
											'#liarg':[
												[1,2,3],
												[2,6,3]
											],
											'#kwarg':{
												'linestyle':"",
												'marker':'o'
											}
										}
									)
								]
							}
						}
					},
					'|B':{
						'FiguringDrawVariable':
						[
							(
								'#plot',
								{
									'#liarg':[
										[1,2,3],
										[2,6,3]
									],
									'#kwarg':{
										'linestyle':"",
										'marker':'o'
									}
								}
							)
						]
					},
				}
			},
			'|fig2':{
				'FiguringDrawVariable':
				[
					(
						'#plot',
						{
							'#liarg':[
								[1,2,3],
								[2,6,3]
							],
							'#kwarg':{
								'linestyle':"",
								'marker':'o'
							}
						}
					)
				]
			}
		}
	)

#print
print('MyDrawer is ')
SYS._print(MyDrawer)

