
# ---------------------------------------------------
# This file is autogenerated by git-version.
# DO NOT MODIFY!
# ---------------------------------------------------

VERSION_STRING = "1.5"
GIT_TAG_NAME = "1.5"
GIT_COMMITS_SINCE_TAG = 0
GIT_COMMIT_ID = "0466cc4"
MODIFIED_SINCE_COMMIT = False
IS_DEV_VERSION = False

IS_STABLE_VERSION = True

VERSION_COMPONENTS = ["1", "5"]
VERSION_TAG = ""

