# Autogenerated by Astropy's setup.py on 2015-07-31 19:05:41.552392
from __future__ import unicode_literals
import datetime

version = "1.0.3"
githash = "27fb98c9d0a549556cb9f13f3df4a9d309e5a7ca"


major = 1
minor = 0
bugfix = 3

release = True
timestamp = datetime.datetime(2015, 7, 31, 19, 5, 41, 552392)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
