sudo: false
language: python
install:
      - pip install tox 
script:
      - tox
env:
      - TOXENV=py27
      - TOXENV=py32
      - TOXENV=py33
      - TOXENV=py34
      - TOXENV=pypy
      - TOXENV=pypy3
      - TOXENV=pep8

notifications:
      irc: "chat.freenode.net#gabbi"
