
# This file was generated by 'versioneer.py' (0.14+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "638b6e44b10967cff131a59a66f4017e7bd84ff5",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
