# Generated by setup.py for PyCBC on 2015-07-22 20:21:32 +0000.

version = '1.1.0'
date = '2015-07-22 20:20:19 +0000'
release = True

git_hash = 'dc5547098e9df1153bf134795a38c0409650cd34'
git_branch = 'master'
git_tag = 'v1.1.0'
git_author = 'Alexander Harvey Nitz <alex.nitz@gmail.com>'
git_committer = 'Alexander Harvey Nitz <alex.nitz@gmail.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Alexander Harvey Nitz <alex.nitz@gmail.com>'
git_build_date = '2015-07-22 20:21:32 +0000'
git_verbose_msg = """Branch: master
Tag: v1.1.0
Id: dc5547098e9df1153bf134795a38c0409650cd34
Builder: Alexander Harvey Nitz <alex.nitz@gmail.com>
Build date: 2015-07-22 20:21:32 +0000
Repository status is CLEAN: All modifications committed"""