# This file was auto-generated by salt's setup on Wednesday, 09 September 2015 @ 20:09:40 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 8, 0, 0, 0, 0, None)
