
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d543ef3eba05357e7aa82aadaf4e737bf6fe63a6",
 "version": "0.1.post39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
