__version__ = "0.4.6"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.4.6)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '94201ef311d003db648639feb255be3bfe7b2f61'
__git_head_subject__ = 'Finished release v0.4.6.'
__git_head_message__ = ''
__git_dirty_diff__ = ''