
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.2'
version_full = '8baf94236657b79abe50e689b708c88c36f14c36'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

