
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a4d2db52a90708569b76fa6f89c6095e24bb889c",
 "version": "0.2.post4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
