
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class FraudScreen(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def screen(self,request):
		""" payments-fraudscreen Post Screen description DOCUMENT_HERE 
		
		Args:
			| request(request) - Mozu.PaymentService.Contracts.Request.FraudScreenRequest ApiType DOCUMENT_HERE 
		
		Returns:
			| FraudScreen 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/payment/commerce/payments/fraudscreen/screen", "POST", UrlLocation.PCIPod, False);
		self.client.withResourceUrl(url).withBody(request).execute();
		return self.client.result();

	
	
	