
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation

class PublicCard(object):
	def __init__(self, mozuClient = None):
		self.client = mozuClient or default_client();
	
	def create(self,request):
		""" payments-cards Post Create description DOCUMENT_HERE 
		
		Args:
			| request(request) - Mozu.PaymentService.Contracts.PublicCard ApiType DOCUMENT_HERE 
		
		Returns:
			| SyncResponse 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/payment/commerce/payments/cards/", "POST", UrlLocation.PCIPod, False);
		self.client.withResourceUrl(url).withBody(request).execute();
		return self.client.result();

	
		
	def update(self,request, cardId):
		""" payments-cards Put Update description DOCUMENT_HERE 
		
		Args:
			| request(request) - Mozu.PaymentService.Contracts.PublicCard ApiType DOCUMENT_HERE 
			| cardId (string) - Unique identifier of the card associated with the customer account billing contact.
		
		Returns:
			| SyncResponse 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/payment/commerce/payments/cards/{cardId}", "PUT", UrlLocation.PCIPod, False);
		url.formatUrl("cardId", cardId);
		self.client.withResourceUrl(url).withBody(request).execute();
		return self.client.result();

	
		
	def delete(self,cardId):
		""" payments-cards Delete Delete description DOCUMENT_HERE 
		
		Args:
			| cardId (string) - Unique identifier of the card associated with the customer account billing contact.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/payment/commerce/payments/cards/{cardId}", "DELETE", UrlLocation.PCIPod, False);
		url.formatUrl("cardId", cardId);
		self.client.withResourceUrl(url).execute();

	
	
	