language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "pypy"
  - "nightly"

# We have to pin Jinja2 < 2.7  for Python 3.2 because 2.7 drops/breaks support:
# http://jinja.pocoo.org/docs/changelog/#version-2-7
# And Spinx to < 1.3 for pypy3 and python 3.2 similarly.
#
# See also:
# http://stackoverflow.com/questions/18252804/syntax-error-in-jinja-2-library
matrix:
  include:
    - python: "3.2"
      env:
        - JINJA_REQ="jinja2<2.7, Pygments<2.0"
        - SPHINX="<1.3"
    - python: "pypy3"
      env: SPHINX="<1.3"

install:
  - pip install -U pip
  - pip install -U wheel setuptools
# parsley git supports 3.x
  - pip install git+https://github.com/python-parsley/parsley.git .[test]

script:
  - python -m testtools.run discover 
  - rst2html.py README.rst README.html
