class_dumps: class_dumps
lldb_init:
  - lldbinit
dependencies:
  - Foundation
modules:
  - SKDownload
  - SKPayment
  - SKPaymentInternal
  - SKPaymentQueue
  - SKPaymentQueueInternal
  - SKPaymentTransaction
  - SKPaymentTransactionInternal
  - SKProduct
  - SKProductInternal
  - SKRequest
  - SKRequestInternal
  - SKProductsRequest
  - SKProductsRequestInternal
  - SKProductsResponse
  - SKProductsResponseInternal
  - SKReceiptRefreshRequest
load_all_modules: false
