
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6d3e4f02885ea07e28e9d3f073ad9c402603c705",
 "version": "0.1.post7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
