
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "32417038e62d57b9d94872a9e18b997b403f0e42",
 "version": "0.22.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
