
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f1b42c6a69af5544ce1f39584208f4dab3c793d8",
 "version": "0.3.post15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
