__title__ = 'pyramid_cli'
__summary__ = 'Tools for managing pyramid applications!'
__uri__ = 'http://github.com/surveymonkey/pyramid_cli'
__version__ = '0.0.2'
__author__ = 'John Anderson'
__email__ = 'johna@surveymonkey.com'
__license__ = 'MIT'
__copyright__ = '2015 SurveyMonkey'
