class_dumps: class_dumps
lldb_init:
  - lldbinit
dependencies:
  - Foundation
  - CoreGraphics
modules:
  - UIEdgeInsets
  - UIOffset

  - UIAlertAction
  - UIColor
  - UIDeviceRGBColor
  - UIDeviceWhiteColor
  - UIBarItem
  - UIBarButtonItem
  - UIEvent
  - UIImage
  - UINib
  - UINibStorage
  - UIScreen
  - UIStoryboard
  - UIStoryboardSegue
  - UITouch
  - UIInternalEvent
  - UITouchesEvent

  - UIResponder
  - UIView
  - UIAlertView
  - UIActivityIndicatorView
  - UIImageView
  - UILabel
  - UIPickerView
  - UIDatePickerView
  - UIProgressView
  - UIScrollView
  - UITableViewCell

  - UIControl
  - UIButton
  - UIDatePicker
  - UIPageControl
  - UISegmentedControl
  - UISlider
  - UIStepper
  - UISwitch
  - UITextField

  - UIViewController
  - UINavigationController
  - UIAlertController
load_all_modules: false
