
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "17be0be9b7a55b48359e80657b746f778f507129",
 "version": "0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
