# This file was auto-generated by zetup
#
# https://bitbucket.org/userzimmermann/zetup.py


from __future__ import absolute_import

import sys
import os
from collections import OrderedDict

from zetup.version import Version
from zetup.dist import Distribution
from zetup.requires import Requirements
from zetup.extras import Extras
from zetup.package import Packages, Package
from zetup.notebook import Notebook



zfg = sys.modules[__name__]

LICENSE = 'LGPLv3'

TITLE = 'modeled'

PYTHON = ['2.7', '3.3', '3.4']

MODULES = []

KEYWORDS = ['modeled', 'model', 'modeling', 'modelled', 'modelling', 'serialization', 'exchange', 'mapping', 'class', 'object', 'member', 'property', 'typed', 'ctypes', 'cfunc', 'funcptr', 'python3']

PACKAGES = Packages([

Package('modeled',
  sources=[
    'meta.py',
    'extension.py',
    'options.py',
    'range.py',
    'model.py',
    '__init__.py',
    'datetime.py',
    'namedtuple.py',
    'list.py',
    'simpledict.py',
    'adapter.py',
    'object.py',
    'typed.py',
    'dict.py',
    'tuple.py',
    'base.py'
    ],
  subpackages=[
    
Package('modeled.member',
  sources=[
    '__init__.py',
    'list.py',
    'handlers.py',
    'context.py',
    'dict.py',
    'tuple.py'
    ],
  subpackages=[
    
    ],
  )
,
    
Package('modeled.cfunc',
  sources=[
    'arg.py',
    'model.py',
    '__init__.py'
    ],
  subpackages=[
    
    ],
  )
,
    
Package('modeled.property',
  sources=[
    '__init__.py',
    'list.py',
    'dict.py'
    ],
  subpackages=[
    
    ],
  )

    ],
  )

  ], root=os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

EMAIL = 'zimmermann.code@gmail.com'

AUTHOR = 'Stefan Zimmermann'

REQUIRES = Requirements("""
six >= 1.9
path.py >= 8.0 #import path
moretools >= 0.1.7
zetup >= 0.2.21

""", zfg=zfg)

URL = 'https://bitbucket.org/userzimmermann/python-modeled'

SETUP_HOOKS = []

VERSION = Version('0.1.6')

NAME = 'modeled'

DESCRIPTION = 'Universal data modeling for Python.'

SETUP_REQUIRES = None

EXTRAS = Extras([

], zfg=zfg)

DISTRIBUTION = Distribution('modeled', 'modeled', '0.1.6')

CLASSIFIERS = ['Development Status :: 3 - Alpha', 'Intended Audience :: Developers', 'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)', 'Operating System :: OS Independent', 'Topic :: Software Development', 'Topic :: Utilities', 'Programming Language :: Python', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3.3', 'Programming Language :: Python :: 3.4']