
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.0'
version_full = 'a5fbec41c991bf5d3919028c5b2e2b34c77a2112'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

