
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4973eafa5c463f79bd045221acdf290c23c7c34b",
 "version": "0.2.post26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
