package:
  name: impyla
  version: "0.11.2"

source:
  fn: impyla-0.11.2.tar.gz
  url: https://pypi.python.org/packages/source/i/impyla/impyla-0.11.2.tar.gz
  md5: 350385753a8eecf1408e419586df0e9d

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - six
    - thrift_sasl
    - bitarray
    - thrift
    - llvmpy
    - numba

  run:
    - python
    - setuptools
    - six
    - thrift_sasl
    - bitarray
    - thrift
    - llvmpy
    - numba

test:
  imports:
    - impala
    - impala._thrift_api
    - impala._thrift_gen
    - impala._thrift_gen.ExecStats
    - impala._thrift_gen.ImpalaService
    - impala._thrift_gen.Status
    - impala._thrift_gen.TCLIService
    - impala._thrift_gen.Types
    - impala._thrift_gen.beeswax
    - impala._thrift_gen.fb303
    - impala._thrift_gen.hive_metastore
    - impala.tests
    - impala.thrift
    # - impala.udf  # Test fails on osx-64

about:
  home: https://github.com/cloudera/impyla
  license: Apache License, Version 2.0
  summary: 'Python client for the Impala distributed query engine'
