language: python
python:
    - '2.6'
    - '2.7'
    - '3.3'
    - '3.4'
    - nightly

matrix:
    allow_failures:
        - python: nightly

install: pip install tox

script:
    - tox -e py
    - tox -e flake8
