
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4855bed3109fedcf7b33525dc6e679bf272e3e00",
 "version": "15.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
