
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "98012ae1cc1d9d89fa4cf09d697ca74da16e7520",
 "version": "0.2.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
