
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.9'
version_full = '2868c5708b9d9d93b2a9e0f6dab1efa25820d6c1'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

