
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b83bb312e9292ba8f61cc81a6f72a4d4f97fc983",
 "version": "0.1.post4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
