
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.3'
version_full = 'f6a893aeb25c5991f739e44d045ec8cd910a844f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

