__version__ = "0.6.43"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.6.43)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '306efebd72fcb0b8a81ce28f0bc01dc46841c6fc'
__git_head_subject__ = 'Finished release v0.6.43.'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2015-09-09 15:56:33'
