
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.3'
version_full = '476440b2953de7aa4c1c0ac72eae4f9f165fa9f5'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

