sudo: false
language: python
python:
  - 2.7
cache:
  directories:
    - buildout-cache
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap-buildout.py
  - bin/buildout
script:
  - bin/test

notifications:
  email:
    - steve@dcn.org