
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "54ea8aa45c853a48a6931c345fd11f8ebd4b9d60",
 "version": "0.1.post2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
