
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.14'
version_full = '59a660e69f2cdc6a57fe319464e81ab4dc19c2cc'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

