

http_server:
    ip_addr: [ 192.168.0.1, 192.168.0.2 ]
    port: 8080

database:
    ip_addr: 192.168.0.1
    password: pwd!!$
    port: 4444

send_email_on_error: yes

syslog_server: 192.168.0.254
