__version__ = "0.3.5"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.3.5)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '63fd2f449278d3b5f6f124bcce97fb57531ab2a6'
__git_head_subject__ = 'Finished release v0.3.5.'
__git_head_message__ = ''
__git_dirty_diff__ = ''