
# This file was generated by 'versioneer.py' (0.13+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2'
version_full = 'd3f1f3a584bf1ab37b7b8ae6248febf5eec8b56d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

