language: python
python: 2.7
sudo: false
env:
  global:
    MANHOLE_TEST_TIMEOUT=30
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
    - TOXENV=2.6,coveralls,codecov
    - TOXENV=2.6-eventlet,coveralls,codecov
    - TOXENV=2.6-eventlet-nocover
    - TOXENV=2.6-eventlet-nocover-patchthread
    - TOXENV=2.6-eventlet-patchthread,coveralls,codecov
    - TOXENV=2.6-gevent,coveralls,codecov
    - TOXENV=2.6-gevent-nocover
    - TOXENV=2.6-gevent-nocover-patchthread
    - TOXENV=2.6-gevent-patchthread,coveralls,codecov
    - TOXENV=2.6-nocover
    - TOXENV=2.6-signalfd,coveralls,codecov
    - TOXENV=2.6-signalfd-eventlet,coveralls,codecov
    - TOXENV=2.6-signalfd-eventlet-nocover
    - TOXENV=2.6-signalfd-eventlet-nocover-patchthread
    - TOXENV=2.6-signalfd-eventlet-patchthread,coveralls,codecov
    - TOXENV=2.6-signalfd-gevent,coveralls,codecov
    - TOXENV=2.6-signalfd-gevent-nocover
    - TOXENV=2.6-signalfd-gevent-nocover-patchthread
    - TOXENV=2.6-signalfd-gevent-patchthread,coveralls,codecov
    - TOXENV=2.6-signalfd-nocover
    - TOXENV=2.7,coveralls,codecov
    - TOXENV=2.7-eventlet,coveralls,codecov
    - TOXENV=2.7-eventlet-nocover
    - TOXENV=2.7-eventlet-nocover-patchthread
    - TOXENV=2.7-eventlet-patchthread,coveralls,codecov
    - TOXENV=2.7-gevent,coveralls,codecov
    - TOXENV=2.7-gevent-nocover
    - TOXENV=2.7-gevent-nocover-patchthread
    - TOXENV=2.7-gevent-patchthread,coveralls,codecov
    - TOXENV=2.7-nocover
    - TOXENV=2.7-signalfd,coveralls,codecov
    - TOXENV=2.7-signalfd-eventlet,coveralls,codecov
    - TOXENV=2.7-signalfd-eventlet-nocover
    - TOXENV=2.7-signalfd-eventlet-nocover-patchthread
    - TOXENV=2.7-signalfd-eventlet-patchthread,coveralls,codecov
    - TOXENV=2.7-signalfd-gevent,coveralls,codecov
    - TOXENV=2.7-signalfd-gevent-nocover
    - TOXENV=2.7-signalfd-gevent-nocover-patchthread
    - TOXENV=2.7-signalfd-gevent-patchthread,coveralls,codecov
    - TOXENV=2.7-signalfd-nocover
    - TOXENV=3.2,coveralls,codecov
    - TOXENV=3.2-eventlet,coveralls,codecov
    - TOXENV=3.2-eventlet-nocover
    - TOXENV=3.2-eventlet-nocover-patchthread
    - TOXENV=3.2-eventlet-patchthread,coveralls,codecov
    - TOXENV=3.2-gevent,coveralls,codecov
    - TOXENV=3.2-gevent-nocover
    - TOXENV=3.2-gevent-nocover-patchthread
    - TOXENV=3.2-gevent-patchthread,coveralls,codecov
    - TOXENV=3.2-nocover
    - TOXENV=3.2-signalfd,coveralls,codecov
    - TOXENV=3.2-signalfd-eventlet,coveralls,codecov
    - TOXENV=3.2-signalfd-eventlet-nocover
    - TOXENV=3.2-signalfd-eventlet-nocover-patchthread
    - TOXENV=3.2-signalfd-eventlet-patchthread,coveralls,codecov
    - TOXENV=3.2-signalfd-gevent,coveralls,codecov
    - TOXENV=3.2-signalfd-gevent-nocover
    - TOXENV=3.2-signalfd-gevent-nocover-patchthread
    - TOXENV=3.2-signalfd-gevent-patchthread,coveralls,codecov
    - TOXENV=3.2-signalfd-nocover
    - TOXENV=3.3,coveralls,codecov
    - TOXENV=3.3-eventlet,coveralls,codecov
    - TOXENV=3.3-eventlet-nocover
    - TOXENV=3.3-eventlet-nocover-patchthread
    - TOXENV=3.3-eventlet-patchthread,coveralls,codecov
    - TOXENV=3.3-gevent,coveralls,codecov
    - TOXENV=3.3-gevent-nocover
    - TOXENV=3.3-gevent-nocover-patchthread
    - TOXENV=3.3-gevent-patchthread,coveralls,codecov
    - TOXENV=3.3-nocover
    - TOXENV=3.3-signalfd,coveralls,codecov
    - TOXENV=3.3-signalfd-eventlet,coveralls,codecov
    - TOXENV=3.3-signalfd-eventlet-nocover
    - TOXENV=3.3-signalfd-eventlet-nocover-patchthread
    - TOXENV=3.3-signalfd-eventlet-patchthread,coveralls,codecov
    - TOXENV=3.3-signalfd-gevent,coveralls,codecov
    - TOXENV=3.3-signalfd-gevent-nocover
    - TOXENV=3.3-signalfd-gevent-nocover-patchthread
    - TOXENV=3.3-signalfd-gevent-patchthread,coveralls,codecov
    - TOXENV=3.3-signalfd-nocover
    - TOXENV=3.4,coveralls,codecov
    - TOXENV=3.4-eventlet,coveralls,codecov
    - TOXENV=3.4-eventlet-nocover
    - TOXENV=3.4-eventlet-nocover-patchthread
    - TOXENV=3.4-eventlet-patchthread,coveralls,codecov
    - TOXENV=3.4-gevent,coveralls,codecov
    - TOXENV=3.4-gevent-nocover
    - TOXENV=3.4-gevent-nocover-patchthread
    - TOXENV=3.4-gevent-patchthread,coveralls,codecov
    - TOXENV=3.4-nocover
    - TOXENV=3.4-signalfd,coveralls,codecov
    - TOXENV=3.4-signalfd-eventlet,coveralls,codecov
    - TOXENV=3.4-signalfd-eventlet-nocover
    - TOXENV=3.4-signalfd-eventlet-nocover-patchthread
    - TOXENV=3.4-signalfd-eventlet-patchthread,coveralls,codecov
    - TOXENV=3.4-signalfd-gevent,coveralls,codecov
    - TOXENV=3.4-signalfd-gevent-nocover
    - TOXENV=3.4-signalfd-gevent-nocover-patchthread
    - TOXENV=3.4-signalfd-gevent-patchthread,coveralls,codecov
    - TOXENV=3.4-signalfd-nocover
    - TOXENV=pypy,coveralls,codecov
    - TOXENV=pypy-nocover
    - TOXENV=pypy-signalfd,coveralls,codecov
    - TOXENV=pypy-signalfd-nocover
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
  - |
    if [[ "${TOXENV}" =~ "pypy" ]]; then
        git clone https://github.com/yyuu/pyenv.git ~/.pyenv
        PYENV_ROOT="$HOME/.pyenv"
        PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv install pypy-2.6.0
        pyenv global pypy-2.6.0
    fi
    pip install virtualenv
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always

