language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
    - TOXENV=2.6,coveralls,codecov
    - TOXENV=2.6-pdbpp,coveralls,codecov
    - TOXENV=2.6-nocover
    - TOXENV=2.6-nocover-pdbpp
    - TOXENV=2.7,coveralls,codecov
    - TOXENV=2.7-pdbpp,coveralls,codecov
    - TOXENV=2.7-nocover
    - TOXENV=2.7-nocover-pdbpp
    - TOXENV=3.3,coveralls,codecov
    - TOXENV=3.3-pdbpp,coveralls,codecov
    - TOXENV=3.3-nocover
    - TOXENV=3.3-nocover-pdbpp
    - TOXENV=3.4,coveralls,codecov
    - TOXENV=3.4-pdbpp,coveralls,codecov
    - TOXENV=3.4-nocover
    - TOXENV=3.4-nocover-pdbpp
    - TOXENV=pypy,coveralls,codecov
    - TOXENV=pypy-pdbpp,coveralls,codecov
    - TOXENV=pypy-nocover
    - TOXENV=pypy-nocover-pdbpp
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always

