__version__ = "0.0.8"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.0.8)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '4bc349cf2a5087e1d3b42bba5bbefc694cdda3b4'
__git_head_subject__ = 'Finished release v0.0.8.'
__git_head_message__ = ''
__git_dirty_diff__ = ''