
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.3'
version_full = '065b69ab131607eb95a48db9d8bb7b31e8cc2bfa'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

