
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.8'
version_full = '1699a88e693fb06b95ca36c9594806f4cc73467f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

