
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ac438e3d25c3b8931b24dcd2aaf0561c30c87d54",
 "version": "1.4.0.pre0.post.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
