
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1e60827458c870da4f39e521bab8d1e23454b903",
 "version": "0.3.post12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
