sudo: true
language: python
python:
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"
env:
    - BUILD=test DAV_SERVER=radicale RADICALE_BACKEND=filesystem REQUIREMENTS=release
      # Radicale with filesystem storage (default)

    - BUILD=test DAV_SERVER=radicale RADICALE_BACKEND=filesystem REQUIREMENTS=release
      PKGS='lxml==3.0 requests==2.4.1 requests_toolbelt==0.4.0 click==3.1'
      # Minimal requirements

    - BUILD=test DAV_SERVER=radicale RADICALE_BACKEND=filesystem REQUIREMENTS=devel
      # Radicale-git with filesystem storage (default)

    - BUILD=test DAV_SERVER=owncloud REQUIREMENTS=release
      # Latest ownCloud release

    - BUILD=test DAV_SERVER=baikal REQUIREMENTS=release
      # Latest Baikal release

    - BUILD=style
      # flake8 with plugins

install:
    - "pip install -U pip"
    - "pip install wheel"
    - "pip install -e ."
    - "make -e install-$BUILD"
    - '[ -z "$PKGS" ] || pip install $PKGS'
script:
    - "make -e $BUILD"
