
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.0'
version_full = '64f6f3f20fdc9cc9afb44685aaa268632ea3aec8'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

