# the root path your site will be served. e.g. "/mysite", (default: "", no sub_path)
root = ""

[blog]
name = "编程小梦"
description = "康凯森的技术博客"
theme = "clr"  # path to theme

[author]
name = "康凯森"
email = "kangkaisen@126.com"
description = "大数据开发工程师"
url = "http://www.bcmeng.com/"  # author's index url

[disqus]
enable = false  # enable comment? true or false
shortname = "kks"  # shortname from disqus.com

[theme]
email_public = false
github = "kangkaisen"
twitter = ""
dribbble = ""
pdf_link = "/out.pdf"
