
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cd2e373bf1fe9b385d53bf3ff5236fc521e971b9",
 "version": "1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
