
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ab930969d12aee3da31e05cf56e7f8d1bfb797e8",
 "version": "0.1.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
