language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    # - pypy
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -U ipaddress unittest2 mock==1.0.1; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -U ipaddress mock; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install -U ipaddress mock; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install -U ipaddress; fi
    - pip install coverage coveralls
script:
    - pip install flake8 pep8
    - python setup.py build
    - python setup.py install
    - coverage run test/test_psutil.py --include="*psutil*" --omit="test/*,*setup*"
    - python test/test_memory_leaks.py
    - flake8
    - pep8
os:
    - linux
    - osx  # currently not supported by travis
after_success:
  - coveralls  # upload reports to coveralls.io
