# -*- coding: utf-8 -*-

COMMUNES = [
    u'Aisén',
    u'Algarrobo',
    u'Alhué',
    u'Alto Hospicio',
    u'Ancud',
    u'Andacollo',
    u'Angol',
    u'Antofagasta',
    u'Antuco',
    u'Arauco',
    u'Arica',
    u'Buin',
    u'Bulnes',
    u'Cabildo',
    u'Cabo de Hornos',
    u'Cabrero',
    u'Calama',
    u'Calbuco',
    u'Caldera',
    u'Calera de Tango',
    u'Calera',
    u'Calle Larga',
    u'Canela',
    u'Carahue',
    u'Cartagena',
    u'Casablanca',
    u'Castro',
    u'Catemu',
    u'Cauquenes',
    u'Cañete',
    u'Cerrillos',
    u'Cerro Navia',
    u'Chaitén',
    u'Chanco',
    u'Chañaral',
    u'Chiguayante',
    u'Chile Chico',
    u'Chillán Viejo',
    u'Chillán',
    u'Chimbarongo',
    u'Cholchol',
    u'Chonchi',
    u'Chépica',
    u'Cisnes',
    u'Cobquecura',
    u'Cochamó',
    u'Cochrane',
    u'Coelemu',
    u'Coihaique',
    u'Coihueco',
    u'Colbún',
    u'Colina',
    u'Collipulli',
    u'Coltauco',
    u'Combarbalá',
    u'Concepción',
    u'Conchalí',
    u'Concón',
    u'Constitución',
    u'Contulmo',
    u'Copiapó',
    u'Coquimbo',
    u'Coronel',
    u'Corral',
    u'Cunco',
    u'Curacautín',
    u'Curacaví',
    u'Curanilahue',
    u'Curarrehue',
    u'Curepto',
    u'Curicó',
    u'Dalcahue',
    u'Diego de Almagro',
    u'Doñihue',
    u'El Bosque',
    u'El Carmen',
    u'El Monte',
    u'El Quisco',
    u'Empedrado',
    u'Ercilla',
    u'Estación Central',
    u'Florida',
    u'Freire',
    u'Fresia',
    u'Frutillar',
    u'Futrono',
    u'Galvarino',
    u'Gorbea',
    u'Graneros',
    u'Guaitecas',
    u'Hijuelas',
    u'Hualaihué',
    u'Hualañé',
    u'Hualpén',
    u'Huasco',
    u'Huechuraba',
    u'Illapel',
    u'Independencia',
    u'Iquique',
    u'Isla de Maipo',
    u'Isla de Pascua',
    u'La Cisterna',
    u'La Cruz',
    u'La Estrella',
    u'La Florida',
    u'La Granja',
    u'La Ligua',
    u'La Pintana',
    u'La Reina',
    u'La Serena',
    u'La Unión',
    u'Lago Ranco',
    u'Laja',
    u'Lampa',
    u'Lanco',
    u'Las Cabras',
    u'Las Condes',
    u'Lautaro',
    u'Lebu',
    u'Licantén',
    u'Limache',
    u'Linares',
    u'Litueche',
    u'Llaillay',
    u'Llanquihue',
    u'Lo Barnechea',
    u'Lo Espejo',
    u'Lo Prado',
    u'Lolol',
    u'Loncoche',
    u'Longaví',
    u'Lonquimay',
    u'Los Andes',
    u'Los Lagos',
    u'Los Muermos',
    u'Los Sauces',
    u'Los Vilos',
    u'Los Álamos',
    u'Los Ángeles',
    u'Lota',
    u'Lumaco',
    u'Machalí',
    u'Macul',
    u'Maipú',
    u'Malloa',
    u'Marchihue',
    u'Mariquina',
    u'María Elena',
    u'María Pinto',
    u'Maule',
    u'Maullín',
    u'Mejillones',
    u'Melipeuco',
    u'Melipilla',
    u'Molina',
    u'Monte Patria',
    u'Mostazal',
    u'Mulchén',
    u'Máfil',
    u'Nacimiento',
    u'Nancagua',
    u'Natales',
    u'Navidad',
    u'Negrete',
    u'Ninhue',
    u'Nogales',
    u'Nueva Imperial',
    u'Ñiquén',
    u'Ñuñoa',
    u'Olivar',
    u'Olmué',
    u'Osorno',
    u'Ovalle',
    u'OHiggins',
    u'Padre Hurtado',
    u'Padre las Casas',
    u'Paillaco',
    u'Paine',
    u'Palena',
    u'Palmilla',
    u'Panguipulli',
    u'Panquehue',
    u'Papudo',
    u'Paredones',
    u'Parral',
    u'Pedro Aguirre Cerda',
    u'Pelarco',
    u'Pelluhue',
    u'Pemuco',
    u'Pencahue',
    u'Penco',
    u'Peralillo',
    u'Perquenco',
    u'Petorca',
    u'Peumo',
    u'Peñaflor',
    u'Peñalolén',
    u'Pica',
    u'Pichidegua',
    u'Pichilemu',
    u'Pinto',
    u'Pirque',
    u'Pitrufquén',
    u'Placilla',
    u'Porvenir',
    u'Pozo Almonte',
    u'Primavera',
    u'Providencia',
    u'Puchuncaví',
    u'Pucón',
    u'Pudahuel',
    u'Puente Alto',
    u'Puerto Montt',
    u'Puerto Octay',
    u'Puerto Varas',
    u'Pumanque',
    u'Punitaqui',
    u'Punta Arenas',
    u'Purranque',
    u'Purén',
    u'Putaendo',
    u'Puyehue',
    u'Queilén',
    u'Quellón',
    u'Quilicura',
    u'Quillota',
    u'Quillón',
    u'Quilpué',
    u'Quinchao',
    u'Quinta Normal',
    u'Quinta de Tilcoco',
    u'Quintero',
    u'Quirihue',
    u'Rancagua',
    u'Rauco',
    u'Recoleta',
    u'Renaico',
    u'Renca',
    u'Rengo',
    u'Requínoa',
    u'Retiro',
    u'Rinconada',
    u'Romeral',
    u'Ránquil',
    u'Río Bueno',
    u'Río Claro',
    u'Río Ibáñez',
    u'Río Negro',
    u'Saavedra',
    u'Sagrada Familia',
    u'Salamanca',
    u'San Antonio',
    u'San Bernardo',
    u'San Carlos',
    u'San Clemente',
    u'San Esteban',
    u'San Felipe',
    u'San Fernando',
    u'San Gregorio',
    u'San Ignacio',
    u'San Javier',
    u'San Joaquín',
    u'San José de Maipo',
    u'San Miguel',
    u'San Nicolás',
    u'San Pablo',
    u'San Pedro de Atacama',
    u'San Pedro de la Paz',
    u'San Rafael',
    u'San Ramón',
    u'San Vicente',
    u'Santa Bárbara',
    u'Santa Cruz',
    u'Santa Juana',
    u'Santa María',
    u'Santiago',
    u'Santo Domingo',
    u'Sierra Gorda',
    u'Talagante',
    u'Talca',
    u'Talcahuano',
    u'Taltal',
    u'Temuco',
    u'Teno',
    u'Teodoro Schmidt',
    u'Tierra Amarilla',
    u'Tiltil',
    u'Tirúa',
    u'Tocopilla',
    u'Toltén',
    u'Tomé',
    u'Traiguén',
    u'Tucapel',
    u'Valdivia',
    u'Vallenar',
    u'Valparaíso',
    u'Victoria',
    u'Vicuña',
    u'Vilcún',
    u'Villa Alegre',
    u'Villa Alemana',
    u'Villarrica',
    u'Vitacura',
    u'Viña del Mar',
    u'Yerbas Buenas',
    u'Yumbel',
    u'Yungay',
    u'Zapallar'
]

DISTRIBUTORS = [
    u'ABASTIBLE',
    u'APEX',
    u'ATT',
    u'AUTOGASCO',
    u'BALTOLU',
    u'CAVE',
    u'CHILIN',
    u'COC',
    u'COMBUSTIBLES AMADE',
    u'COMBUSTIBLES JCD',
    u'COMERCIAL MAQUI',
    u'COPEC',
    u'CUSTOM SERVICE',
    u'Combustible Alhue',
    u'Combustibles Endless.com',
    u'Combustibles Ortiz',
    u'Coopeserau',
    u'Cremaschi',
    u'DELPA',
    u'ECCO',
    u'ECOGREEN LTDA.',
    u'EL HUIQUE',
    u'ENERSUR S.A.',
    u'FACAZ',
    u'HN',
    u'HOLA!',
    u'J Allel',
    u'JLC',
    u'LIDER S.A.',
    u'LIPIGAS',
    u'PETROBRAS',
    u'PETROJAC',
    u'PETRONEXT',
    u'Puma Verde',
    u'Rafael Letelier Yañez y Cia Ltda',
    u'SERVICENTRO LEAL',
    u'SERVICENTRO SAN MIGUEL',
    u'SERVICENTROS RABALME',
    u'SESA',
    u'SHELL',
    u'SINHEL',
    u'SOCORRO',
    u'SUAREZ COMBUSTIBLES',
    u'SURENERGY',
    u'Sin Bandera',
    u'TERPEL',
    u'Uligas',
    u'VIVA COMBUSTIBLES'
]

FUEL_TYPES = [
    u'gasolina_93',
    u'gasolina_95',
    u'gasolina_97',
    u'glp_vehicular',
    u'gnc',
    u'kerosene',
    u'petroleo_diesel'
]
