# the root path your site will be served. e.g. "/mysite", (default: "", no sub_path)
root = ""

[blog]
name = "Sunshine Every Day"
description = "Never give up, my determination is to chase for success"
theme = "clr"  # path to theme

[author]
name = "Hit9"
email = "nz2324@126.com"
description = "I am a happy boy."
url = "http://hit9.org"  # author's index url

[disqus]
enable = true  # enable comment? true or false
shortname = "rux"  # shortname from disqus.com

[theme]
email_public = false
github = "hit9"
twitter = "nz2324"
dribbble = ""
pdf_link = "/out.pdf"
