
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0e5c2aa46cf7b42de1babb061824a086109d2ed9",
 "version": "0.2.post2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
