
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.1'
version_full = '593f32f2ce8c2e201b2b40ae2c6382b414ab69d5'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

