
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "acb30dfed5524fa2d20e988d08cef0e66ffcdc60",
 "version": "0.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
