
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7e2ebe675a236e23bf9927939f27d29066980956",
 "version": "0.23.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
