__version__ = "1.0.15"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v1.0.15)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '11696c96eec3522878aef17f6d4d92da5d08652a'
__git_head_subject__ = 'Finished release v1.0.15.'
__git_head_message__ = ''
__git_dirty_diff__ = ''