
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "5cb42bac014cbaf95c2a5d38ec2719ff210f69d3",
 "version": "1.4.0.pre4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
