#   _   _   _   _   _   _   _   _
#  / \ / \ / \ / \ / \ / \ / \ / \
# ( n | e | w | s | l | y | n | x )
#  \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Secret Stuff

secret_key: changeme
app_secret_key: changemetoo
super_user: admin
super_user_email: changeme@example.com
super_user_password: admin
super_user_apikey: mj
super_user_org: 'admin'
super_user_timezone: UTC

# The Database URI (This is mandatory!)
sqlalchemy_database_uri: 'postgres://localhost:5432/newslynx'

# API information for the app to know
api_url: http://localhost:5000
api_version: v1

# Filepaths to default recipes + tags to add for each
# new organization.
default_recipes: '~/.newslynx/defaults/recipes.yaml'
default_tags: '~/.newslynx/defaults/tags.yaml'
