branches:
   except:
      - gh-pages

language: python

python:
 - "2.7"

install: 
  - pip install coveralls
  - pip install pytest-cov
  - pip install -r requirements.txt
  - pip install -e .

script:
  - py.test --cov trump

after_success:
  - coveralls