
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.8'
version_full = '8b2404226b7ccf54e5e72b116c7a49c97a798cff'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

