sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - bash travis-install-openjpeg.sh

# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install lxml contextlib2 mock six; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install lxml numpy six; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install lxml numpy six; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then pip install lxml numpy six; fi

# command to run tests
script:
  - python -m unittest discover

notifications:
  email: "john.g.evans.ne@gmail.com"
