"""Application constants."""

INIT = 'initialized'
PREVALID = 'validating'
POSTVALID = 'validated'
PREPARSE = 'parsing'
POSTPARSE = 'parsed'
PREENHANCE = 'enhancing'
POSTENHANCE = 'enhanced'
PREFORMAT = 'formatting'
POSTFORMAT = 'formatted'
PRENAME = 'renaming'
POSTNAME = 'renamed'
DONE = 'finished'
FAILED = 'failed'
