
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.6'
version_full = '656d917f639002b0dab1614cad6af66f6971b2fd'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

