[package]
name = "nahpack"
version = "0.1.0"
description = "HPACK (RFC 7541) library"
authors = ["ijl <ijl@mailbox.org>"]
license = "MPL2"
readme = "README.md"
repository = "https://github.com/ijl/nahpack"


[lib]
name = "nahpack"
path = "src/lib.rs"
crate-type = ["rlib", "dylib", ]


[dev-dependencies]
rustc-serialize = "*"


[profile.release]
opt-level = 3


[profile.bench]
opt-level = 3


[profile.test]
opt-level = 0
