
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "fcd40c7fe5167980b7d0fee9b57b822d62b00494",
 "version": "0.2.post2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
