# AT command strings
RESET_COMMAND = "ATZ"
ECHO_OFF_COMMAND = "ATE0"
HEADER_ON_COMMAND = "ATH1"
SPACES_OFF_COMMAND = "ATS0"
LINEFEED_OFF_COMMAND = "ATL0"
BATTERY_VOLTAGE_COMMAND = "ATRV"
MEMORY_OFF_COMMAND = "ATM0"

SET_PROTOCOL_AUTO_COMMAND = "ATSPA8"
DESCRIBE_PROTOCOL_COMMAND = "ATDP"
DESCRIBE_PROTOCOL_NUMBER_COMMAND = "ATDPN"

DEFAULT_RETRIES = 10
NO_RESULT = "NODATA"
