language: python
python:
  - 2.7
# - 3.3
sudo: false
env:
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.4
  - DJANGO_VERSION=1.9.1a1
matrix:
  allow_failures:
    - python: 2.7
      env: DJANGO_VERSION=1.9.1a1
install:
  - pip install -r requirements.txt
  - pip install -q flake8
  - pip install -q Django==$DJANGO_VERSION --pre
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - pybot DjangoLibrary/tests/
  - flake8 .
after_script:
  - firefox --version
