language: python
python: 2.7

env:
    - TOX_ENV=py26-twlatest
    - TOX_ENV=py26-twtrunk
    - TOX_ENV=py26-tw153
    - TOX_ENV=py26-tw150
    - TOX_ENV=py26-tw140
    - TOX_ENV=py27-twlatest
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=py27-tw153
    - TOX_ENV=py27-tw150
    - TOX_ENV=py27-tw140
    - TOX_ENV=pypy-twlatest
    - TOX_ENV=pypy-twtrunk
    - TOX_ENV=pypy-tw153
    - TOX_ENV=pypy-tw150
    - TOX_ENV=pypy-tw140
    - TOX_ENV=py33-twtrunk
    - TOX_ENV=py34-twtrunk
    - TOX_ENV=pyflakes
    - TOX_ENV=manifest

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=pyflakes

before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://repo.mongodb.org/apt/ubuntu '$(lsb_release -sc)'/mongodb-org/3.0 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
  - "mongod --version"

install:
  - pip install tox coveralls

before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"

script:
  - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    email: false
