
# This file was generated by 'versioneer.py' (0.1.7) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.3'
version_full = 'da4f217f1a6faadf3b3b97648f7c766a150490c1'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

