
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5759f525fb61714e0a7ad7ae44ad5f784077a94f",
 "version": "0.2.post7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
