
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4b6377895832d8d95800294acc4b5c21051b154b",
 "version": "0.1.post5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
