/* File: plasticmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Wed Jul  8 23:11:39 2015
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *plastic_error;
static PyObject *plastic_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_log_error_in_mml__user__routines_typedef)(string,int);
typedef void(*cb_log_warning_in_mml__user__routines_typedef)(string,int);
typedef void(*cb_log_message_in_mml__user__routines_typedef)(string,int);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
  fprintf(stderr,"plastic.error is related to ");\
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");

\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#define pyobj_from_string1size(v,len) (PyUString_FromStringAndSize((char *)v, len))
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define SWAP(a,b,t) {\
  t *c;\
  c = a;\
  a = b;\
  b = c;}

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(plastic_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = plastic_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = plastic_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (arr->descr->elsize)*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,arr->data,*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = plastic_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
  PyObject *tmp = NULL;
  PyObject *tmp_fun = NULL;
  int tot,opt,ext,siz,i,di=0;
  CFUNCSMESS("create_cb_arglist\n");
  tot=opt=ext=siz=0;
  /* Get the total number of arguments */
  if (PyFunction_Check(fun))
    tmp_fun = fun;
  else {
    di = 1;
    if (PyObject_HasAttrString(fun,"im_func")) {
      tmp_fun = PyObject_GetAttrString(fun,"im_func");
    }
    else if (PyObject_HasAttrString(fun,"__call__")) {
      tmp = PyObject_GetAttrString(fun,"__call__");
      if (PyObject_HasAttrString(tmp,"im_func"))
        tmp_fun = PyObject_GetAttrString(tmp,"im_func");
      else {
        tmp_fun = fun; /* built-in function */
        tot = maxnofargs;
        if (xa != NULL)
          tot += PyTuple_Size((PyObject *)xa);
      }
      Py_XDECREF(tmp);
    }
    else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        tot += PyTuple_Size((PyObject *)xa);
      tmp_fun = fun;
    }
    else if (F2PyCapsule_Check(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
      if(ext>0) {
        fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
        goto capi_fail;
      }
      tmp_fun = fun;
    }
  }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__code__")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_code")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
      tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
    Py_XDECREF(tmp);
  }
  /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
      opt = PyTuple_Size(tmp);
    Py_XDECREF(tmp);
  }
  /* Get the number of extra arguments */
  if (xa != NULL)
    ext = PyTuple_Size((PyObject *)xa);
  /* Calculate the size of call-backs argument list */
  siz = MIN(maxnofargs+ext,tot);
  *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
  fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
  if (siz<tot-opt) {
    fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
    goto capi_fail;
  }
  /* Initialize argument list */
  *args = (PyTupleObject *)PyTuple_New(siz);
  for (i=0;i<*nofargs;i++) {
    Py_INCREF(Py_None);
    PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
  }
  if (xa != NULL)
    for (i=(*nofargs);i<siz;i++) {
      tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
      Py_INCREF(tmp);
      PyTuple_SET_ITEM(*args,i,tmp);
    }
  CFUNCSMESS("create_cb_arglist-end\n");
  return 1;
capi_fail:
  if ((PyErr_Occurred())==NULL)
    PyErr_SetString(plastic_error,errmess);
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(umat,UMAT)(double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,string,int*,int*,int*,int*,double*,int*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,size_t);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/******************* cb_log_message_in_mml__user__routines *******************/
PyObject *cb_log_message_in_mml__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_log_message_in_mml__user__routines_args_capi = NULL;
int cb_log_message_in_mml__user__routines_nofargs = 0;
jmp_buf cb_log_message_in_mml__user__routines_jmpbuf;
/*typedef void(*cb_log_message_in_mml__user__routines_typedef)(string,int);*/
extern void F_FUNC_US(log_message,LOG_MESSAGE) (string message,int message_cb_len) {
  PyTupleObject *capi_arglist = cb_log_message_in_mml__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_log_message_in_mml__user__routines (maxnofargs=1(-0))\n");
  CFUNCSMESSPY("cb:cb_log_message_in_mml__user__routines_capi=",cb_log_message_in_mml__user__routines_capi);
  if (cb_log_message_in_mml__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_log_message_in_mml__user__routines_capi = PyObject_GetAttrString(plastic_module,"log_message");
  }
  if (cb_log_message_in_mml__user__routines_capi==NULL) {
    PyErr_SetString(plastic_error,"cb: Callback log_message not defined (as an argument or module plastic attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_log_message_in_mml__user__routines_capi)) {
  cb_log_message_in_mml__user__routines_typedef cb_log_message_in_mml__user__routines_cptr;
  cb_log_message_in_mml__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_log_message_in_mml__user__routines_capi);
  (*cb_log_message_in_mml__user__routines_cptr)(message,message_cb_len);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(plastic_module,"log_message_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(plastic_error,"Failed to convert plastic.log_message_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(plastic_error,"Callback log_message argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
/*pyobjfrom*/
  if (cb_log_message_in_mml__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_string1size(message,message_cb_len)))
      goto capi_fail;
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function log_message.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_log_message_in_mml__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  CFUNCSMESS("cb:cb_log_message_in_mml__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_log_message_in_mml__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_log_message_in_mml__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/**************** end of cb_log_message_in_mml__user__routines ****************/


/******************* cb_log_warning_in_mml__user__routines *******************/
PyObject *cb_log_warning_in_mml__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_log_warning_in_mml__user__routines_args_capi = NULL;
int cb_log_warning_in_mml__user__routines_nofargs = 0;
jmp_buf cb_log_warning_in_mml__user__routines_jmpbuf;
/*typedef void(*cb_log_warning_in_mml__user__routines_typedef)(string,int);*/
extern void F_FUNC_US(log_warning,LOG_WARNING) (string message,int message_cb_len) {
  PyTupleObject *capi_arglist = cb_log_warning_in_mml__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_log_warning_in_mml__user__routines (maxnofargs=1(-0))\n");
  CFUNCSMESSPY("cb:cb_log_warning_in_mml__user__routines_capi=",cb_log_warning_in_mml__user__routines_capi);
  if (cb_log_warning_in_mml__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_log_warning_in_mml__user__routines_capi = PyObject_GetAttrString(plastic_module,"log_warning");
  }
  if (cb_log_warning_in_mml__user__routines_capi==NULL) {
    PyErr_SetString(plastic_error,"cb: Callback log_warning not defined (as an argument or module plastic attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_log_warning_in_mml__user__routines_capi)) {
  cb_log_warning_in_mml__user__routines_typedef cb_log_warning_in_mml__user__routines_cptr;
  cb_log_warning_in_mml__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_log_warning_in_mml__user__routines_capi);
  (*cb_log_warning_in_mml__user__routines_cptr)(message,message_cb_len);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(plastic_module,"log_warning_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(plastic_error,"Failed to convert plastic.log_warning_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(plastic_error,"Callback log_warning argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
/*pyobjfrom*/
  if (cb_log_warning_in_mml__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_string1size(message,message_cb_len)))
      goto capi_fail;
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function log_warning.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_log_warning_in_mml__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  CFUNCSMESS("cb:cb_log_warning_in_mml__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_log_warning_in_mml__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_log_warning_in_mml__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/**************** end of cb_log_warning_in_mml__user__routines ****************/


/******************** cb_log_error_in_mml__user__routines ********************/
PyObject *cb_log_error_in_mml__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_log_error_in_mml__user__routines_args_capi = NULL;
int cb_log_error_in_mml__user__routines_nofargs = 0;
jmp_buf cb_log_error_in_mml__user__routines_jmpbuf;
/*typedef void(*cb_log_error_in_mml__user__routines_typedef)(string,int);*/
extern void F_FUNC_US(log_error,LOG_ERROR) (string message,int message_cb_len) {
  PyTupleObject *capi_arglist = cb_log_error_in_mml__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_log_error_in_mml__user__routines (maxnofargs=1(-0))\n");
  CFUNCSMESSPY("cb:cb_log_error_in_mml__user__routines_capi=",cb_log_error_in_mml__user__routines_capi);
  if (cb_log_error_in_mml__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_log_error_in_mml__user__routines_capi = PyObject_GetAttrString(plastic_module,"log_error");
  }
  if (cb_log_error_in_mml__user__routines_capi==NULL) {
    PyErr_SetString(plastic_error,"cb: Callback log_error not defined (as an argument or module plastic attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_log_error_in_mml__user__routines_capi)) {
  cb_log_error_in_mml__user__routines_typedef cb_log_error_in_mml__user__routines_cptr;
  cb_log_error_in_mml__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_log_error_in_mml__user__routines_capi);
  (*cb_log_error_in_mml__user__routines_cptr)(message,message_cb_len);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(plastic_module,"log_error_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(plastic_error,"Failed to convert plastic.log_error_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(plastic_error,"Callback log_error argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
/*pyobjfrom*/
  if (cb_log_error_in_mml__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_string1size(message,message_cb_len)))
      goto capi_fail;
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function log_error.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_log_error_in_mml__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  CFUNCSMESS("cb:cb_log_error_in_mml__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_log_error_in_mml__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_log_error_in_mml__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_log_error_in_mml__user__routines *****************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ umat ************************************/
static char doc_f2py_rout_plastic_umat[] = "\
umat(stress,statev,ddsdde,sse,spd,scd,rpl,ddsddt,drplde,drpldt,stran,dstran,time,dtime,temp,dtemp,predef,dpred,cmname,ndi,nshr,nstatv,props,coords,drot,pnewdt,celent,dfgrd0,dfgrd1,noel,npt,layer,kspt,kstep,kinc,log_message,log_warning,log_error,[ntens,nprops,log_message_extra_args,log_warning_extra_args,log_error_extra_args])\n\nWrapper for ``umat``.\
\n\nParameters\n----------\n"
"stress : in/output rank-1 array('d') with bounds (ntens)\n"
"statev : in/output rank-1 array('d') with bounds (nstatv)\n"
"ddsdde : in/output rank-2 array('d') with bounds (ntens,ntens)\n"
"sse : input float\n"
"spd : input float\n"
"scd : input float\n"
"rpl : input float\n"
"ddsddt : in/output rank-1 array('d') with bounds (ntens)\n"
"drplde : in/output rank-1 array('d') with bounds (ntens)\n"
"drpldt : input float\n"
"stran : input rank-1 array('d') with bounds (ntens)\n"
"dstran : input rank-1 array('d') with bounds (ntens)\n"
"time : input rank-1 array('d') with bounds (2)\n"
"dtime : input float\n"
"temp : input float\n"
"dtemp : input float\n"
"predef : input rank-1 array('d') with bounds (1)\n"
"dpred : input rank-1 array('d') with bounds (1)\n"
"cmname : input string(len=8)\n"
"ndi : input int\n"
"nshr : input int\n"
"nstatv : input int\n"
"props : input rank-1 array('d') with bounds (nprops)\n"
"coords : input rank-1 array('d') with bounds (3)\n"
"drot : input rank-2 array('d') with bounds (3,3)\n"
"pnewdt : input float\n"
"celent : input float\n"
"dfgrd0 : input rank-2 array('d') with bounds (3,3)\n"
"dfgrd1 : input rank-2 array('d') with bounds (3,3)\n"
"noel : input int\n"
"npt : input int\n"
"layer : input int\n"
"kspt : input int\n"
"kstep : input int\n"
"kinc : input int\n"
"log_message : call-back function\n"
"log_warning : call-back function\n"
"log_error : call-back function\n"
"\nOther Parameters\n----------------\n"
"ntens : input int, optional\n    Default: len(ddsddt)\n"
"nprops :  int, optional\n    Default: len(props)\n"
"log_message_extra_args : input tuple, optional\n    Default: ()\n"
"log_warning_extra_args : input tuple, optional\n    Default: ()\n"
"log_error_extra_args : input tuple, optional\n    Default: ()\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def log_message(message): return \n\
  Required arguments:\n"
"    message : input string(len=-1)\n"
"  def log_warning(message): return \n\
  Required arguments:\n"
"    message : input string(len=-1)\n"
"  def log_error(message): return \n\
  Required arguments:\n"
"    message : input string(len=-1)";
/* extern void F_FUNC(umat,UMAT)(double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,string,int*,int*,int*,int*,double*,int*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,size_t); */
static PyObject *f2py_rout_plastic_umat(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,string,int*,int*,int*,int*,double*,int*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *stress = NULL;
  npy_intp stress_Dims[1] = {-1};
  const int stress_Rank = 1;
  PyArrayObject *capi_stress_tmp = NULL;
  int capi_stress_intent = 0;
  PyObject *stress_capi = Py_None;
  double *statev = NULL;
  npy_intp statev_Dims[1] = {-1};
  const int statev_Rank = 1;
  PyArrayObject *capi_statev_tmp = NULL;
  int capi_statev_intent = 0;
  PyObject *statev_capi = Py_None;
  double *ddsdde = NULL;
  npy_intp ddsdde_Dims[2] = {-1, -1};
  const int ddsdde_Rank = 2;
  PyArrayObject *capi_ddsdde_tmp = NULL;
  int capi_ddsdde_intent = 0;
  PyObject *ddsdde_capi = Py_None;
  double sse = 0;
  PyObject *sse_capi = Py_None;
  double spd = 0;
  PyObject *spd_capi = Py_None;
  double scd = 0;
  PyObject *scd_capi = Py_None;
  double rpl = 0;
  PyObject *rpl_capi = Py_None;
  double *ddsddt = NULL;
  npy_intp ddsddt_Dims[1] = {-1};
  const int ddsddt_Rank = 1;
  PyArrayObject *capi_ddsddt_tmp = NULL;
  int capi_ddsddt_intent = 0;
  PyObject *ddsddt_capi = Py_None;
  double *drplde = NULL;
  npy_intp drplde_Dims[1] = {-1};
  const int drplde_Rank = 1;
  PyArrayObject *capi_drplde_tmp = NULL;
  int capi_drplde_intent = 0;
  PyObject *drplde_capi = Py_None;
  double drpldt = 0;
  PyObject *drpldt_capi = Py_None;
  double *stran = NULL;
  npy_intp stran_Dims[1] = {-1};
  const int stran_Rank = 1;
  PyArrayObject *capi_stran_tmp = NULL;
  int capi_stran_intent = 0;
  PyObject *stran_capi = Py_None;
  double *dstran = NULL;
  npy_intp dstran_Dims[1] = {-1};
  const int dstran_Rank = 1;
  PyArrayObject *capi_dstran_tmp = NULL;
  int capi_dstran_intent = 0;
  PyObject *dstran_capi = Py_None;
  double *time = NULL;
  npy_intp time_Dims[1] = {-1};
  const int time_Rank = 1;
  PyArrayObject *capi_time_tmp = NULL;
  int capi_time_intent = 0;
  PyObject *time_capi = Py_None;
  double dtime = 0;
  PyObject *dtime_capi = Py_None;
  double temp = 0;
  PyObject *temp_capi = Py_None;
  double dtemp = 0;
  PyObject *dtemp_capi = Py_None;
  double *predef = NULL;
  npy_intp predef_Dims[1] = {-1};
  const int predef_Rank = 1;
  PyArrayObject *capi_predef_tmp = NULL;
  int capi_predef_intent = 0;
  PyObject *predef_capi = Py_None;
  double *dpred = NULL;
  npy_intp dpred_Dims[1] = {-1};
  const int dpred_Rank = 1;
  PyArrayObject *capi_dpred_tmp = NULL;
  int capi_dpred_intent = 0;
  PyObject *dpred_capi = Py_None;
  string cmname = NULL;
  int slen(cmname);
  PyObject *cmname_capi = Py_None;
  int ndi = 0;
  PyObject *ndi_capi = Py_None;
  int nshr = 0;
  PyObject *nshr_capi = Py_None;
  int ntens = 0;
  PyObject *ntens_capi = Py_None;
  int nstatv = 0;
  PyObject *nstatv_capi = Py_None;
  double *props = NULL;
  npy_intp props_Dims[1] = {-1};
  const int props_Rank = 1;
  PyArrayObject *capi_props_tmp = NULL;
  int capi_props_intent = 0;
  PyObject *props_capi = Py_None;
  int nprops = 0;
  PyObject *nprops_capi = Py_None;
  double *coords = NULL;
  npy_intp coords_Dims[1] = {-1};
  const int coords_Rank = 1;
  PyArrayObject *capi_coords_tmp = NULL;
  int capi_coords_intent = 0;
  PyObject *coords_capi = Py_None;
  double *drot = NULL;
  npy_intp drot_Dims[2] = {-1, -1};
  const int drot_Rank = 2;
  PyArrayObject *capi_drot_tmp = NULL;
  int capi_drot_intent = 0;
  PyObject *drot_capi = Py_None;
  double pnewdt = 0;
  PyObject *pnewdt_capi = Py_None;
  double celent = 0;
  PyObject *celent_capi = Py_None;
  double *dfgrd0 = NULL;
  npy_intp dfgrd0_Dims[2] = {-1, -1};
  const int dfgrd0_Rank = 2;
  PyArrayObject *capi_dfgrd0_tmp = NULL;
  int capi_dfgrd0_intent = 0;
  PyObject *dfgrd0_capi = Py_None;
  double *dfgrd1 = NULL;
  npy_intp dfgrd1_Dims[2] = {-1, -1};
  const int dfgrd1_Rank = 2;
  PyArrayObject *capi_dfgrd1_tmp = NULL;
  int capi_dfgrd1_intent = 0;
  PyObject *dfgrd1_capi = Py_None;
  int noel = 0;
  PyObject *noel_capi = Py_None;
  int npt = 0;
  PyObject *npt_capi = Py_None;
  int layer = 0;
  PyObject *layer_capi = Py_None;
  int kspt = 0;
  PyObject *kspt_capi = Py_None;
  int kstep = 0;
  PyObject *kstep_capi = Py_None;
  int kinc = 0;
  PyObject *kinc_capi = Py_None;
  PyObject *log_message_capi = Py_None;
  PyTupleObject *log_message_xa_capi = NULL;
  PyTupleObject *log_message_args_capi = NULL;
  int log_message_nofargs_capi = 0;
  PyObject *log_warning_capi = Py_None;
  PyTupleObject *log_warning_xa_capi = NULL;
  PyTupleObject *log_warning_args_capi = NULL;
  int log_warning_nofargs_capi = 0;
  PyObject *log_error_capi = Py_None;
  PyTupleObject *log_error_xa_capi = NULL;
  PyTupleObject *log_error_args_capi = NULL;
  int log_error_nofargs_capi = 0;
  static char *capi_kwlist[] = {"stress","statev","ddsdde","sse","spd","scd","rpl","ddsddt","drplde","drpldt","stran","dstran","time","dtime","temp","dtemp","predef","dpred","cmname","ndi","nshr","nstatv","props","coords","drot","pnewdt","celent","dfgrd0","dfgrd1","noel","npt","layer","kspt","kstep","kinc","log_message","log_warning","log_error","ntens","nprops","log_message_extra_args","log_warning_extra_args","log_error_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|OOO!O!O!:plastic.umat",\
    capi_kwlist,&stress_capi,&statev_capi,&ddsdde_capi,&sse_capi,&spd_capi,&scd_capi,&rpl_capi,&ddsddt_capi,&drplde_capi,&drpldt_capi,&stran_capi,&dstran_capi,&time_capi,&dtime_capi,&temp_capi,&dtemp_capi,&predef_capi,&dpred_capi,&cmname_capi,&ndi_capi,&nshr_capi,&nstatv_capi,&props_capi,&coords_capi,&drot_capi,&pnewdt_capi,&celent_capi,&dfgrd0_capi,&dfgrd1_capi,&noel_capi,&npt_capi,&layer_capi,&kspt_capi,&kstep_capi,&kinc_capi,&log_message_capi,&log_warning_capi,&log_error_capi,&ntens_capi,&nprops_capi,&PyTuple_Type,&log_message_xa_capi,&PyTuple_Type,&log_warning_xa_capi,&PyTuple_Type,&log_error_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable layer */
    f2py_success = int_from_pyobj(&layer,layer_capi,"plastic.umat() 32nd argument (layer) can't be converted to int");
  if (f2py_success) {
  /* Processing variable scd */
    f2py_success = double_from_pyobj(&scd,scd_capi,"plastic.umat() 6th argument (scd) can't be converted to double");
  if (f2py_success) {
  /* Processing variable cmname */
  slen(cmname) = 8;
  f2py_success = string_from_pyobj(&cmname,&slen(cmname),"",cmname_capi,"string_from_pyobj failed in converting 19th argument `cmname' of plastic.umat to C string");
  if (f2py_success) {
  /* Processing variable kspt */
    f2py_success = int_from_pyobj(&kspt,kspt_capi,"plastic.umat() 33rd argument (kspt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable log_message */
if (log_message_capi==Py_None) {
  log_message_capi = PyObject_GetAttrString(plastic_module,"log_message");
  if (log_message_capi) {
    if (log_message_xa_capi==NULL) {
      if (PyObject_HasAttrString(plastic_module,"log_message_extra_args")) {
        PyObject* capi_tmp = PyObject_GetAttrString(plastic_module,"log_message_extra_args");
        if (capi_tmp)
          log_message_xa_capi = (PyTupleObject *)PySequence_Tuple(capi_tmp);
        else
          log_message_xa_capi = (PyTupleObject *)Py_BuildValue("()");
        if (log_message_xa_capi==NULL) {
          PyErr_SetString(plastic_error,"Failed to convert plastic.log_message_extra_args to tuple.\n");
          return NULL;
        }
      }
    }
  }
  if (log_message_capi==NULL) {
    PyErr_SetString(plastic_error,"Callback log_message not defined (as an argument or module plastic attribute).\n");
    return NULL;
  }
}

  log_message_nofargs_capi = cb_log_message_in_mml__user__routines_nofargs;
  if (create_cb_arglist(log_message_capi,log_message_xa_capi,1,0,&cb_log_message_in_mml__user__routines_nofargs,&log_message_args_capi,"failed in processing argument list for call-back log_message.")) {
    jmp_buf log_message_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `log_message`.\n");
    SWAP(log_message_capi,cb_log_message_in_mml__user__routines_capi,PyObject);
    SWAP(log_message_args_capi,cb_log_message_in_mml__user__routines_args_capi,PyTupleObject);
    memcpy(&log_message_jmpbuf,&cb_log_message_in_mml__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable spd */
    f2py_success = double_from_pyobj(&spd,spd_capi,"plastic.umat() 5th argument (spd) can't be converted to double");
  if (f2py_success) {
  /* Processing variable rpl */
    f2py_success = double_from_pyobj(&rpl,rpl_capi,"plastic.umat() 7th argument (rpl) can't be converted to double");
  if (f2py_success) {
  /* Processing variable log_warning */
if (log_warning_capi==Py_None) {
  log_warning_capi = PyObject_GetAttrString(plastic_module,"log_warning");
  if (log_warning_capi) {
    if (log_warning_xa_capi==NULL) {
      if (PyObject_HasAttrString(plastic_module,"log_warning_extra_args")) {
        PyObject* capi_tmp = PyObject_GetAttrString(plastic_module,"log_warning_extra_args");
        if (capi_tmp)
          log_warning_xa_capi = (PyTupleObject *)PySequence_Tuple(capi_tmp);
        else
          log_warning_xa_capi = (PyTupleObject *)Py_BuildValue("()");
        if (log_warning_xa_capi==NULL) {
          PyErr_SetString(plastic_error,"Failed to convert plastic.log_warning_extra_args to tuple.\n");
          return NULL;
        }
      }
    }
  }
  if (log_warning_capi==NULL) {
    PyErr_SetString(plastic_error,"Callback log_warning not defined (as an argument or module plastic attribute).\n");
    return NULL;
  }
}

  log_warning_nofargs_capi = cb_log_warning_in_mml__user__routines_nofargs;
  if (create_cb_arglist(log_warning_capi,log_warning_xa_capi,1,0,&cb_log_warning_in_mml__user__routines_nofargs,&log_warning_args_capi,"failed in processing argument list for call-back log_warning.")) {
    jmp_buf log_warning_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `log_warning`.\n");
    SWAP(log_warning_capi,cb_log_warning_in_mml__user__routines_capi,PyObject);
    SWAP(log_warning_args_capi,cb_log_warning_in_mml__user__routines_args_capi,PyTupleObject);
    memcpy(&log_warning_jmpbuf,&cb_log_warning_in_mml__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable dpred */
  dpred_Dims[0]=1;
  capi_dpred_intent |= F2PY_INTENT_IN;
  capi_dpred_tmp = array_from_pyobj(NPY_DOUBLE,dpred_Dims,dpred_Rank,capi_dpred_intent,dpred_capi);
  if (capi_dpred_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 18th argument `dpred' of plastic.umat to C/Fortran array" );
  } else {
    dpred = (double *)(capi_dpred_tmp->data);

  /* Processing variable predef */
  predef_Dims[0]=1;
  capi_predef_intent |= F2PY_INTENT_IN;
  capi_predef_tmp = array_from_pyobj(NPY_DOUBLE,predef_Dims,predef_Rank,capi_predef_intent,predef_capi);
  if (capi_predef_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 17th argument `predef' of plastic.umat to C/Fortran array" );
  } else {
    predef = (double *)(capi_predef_tmp->data);

  /* Processing variable log_error */
if (log_error_capi==Py_None) {
  log_error_capi = PyObject_GetAttrString(plastic_module,"log_error");
  if (log_error_capi) {
    if (log_error_xa_capi==NULL) {
      if (PyObject_HasAttrString(plastic_module,"log_error_extra_args")) {
        PyObject* capi_tmp = PyObject_GetAttrString(plastic_module,"log_error_extra_args");
        if (capi_tmp)
          log_error_xa_capi = (PyTupleObject *)PySequence_Tuple(capi_tmp);
        else
          log_error_xa_capi = (PyTupleObject *)Py_BuildValue("()");
        if (log_error_xa_capi==NULL) {
          PyErr_SetString(plastic_error,"Failed to convert plastic.log_error_extra_args to tuple.\n");
          return NULL;
        }
      }
    }
  }
  if (log_error_capi==NULL) {
    PyErr_SetString(plastic_error,"Callback log_error not defined (as an argument or module plastic attribute).\n");
    return NULL;
  }
}

  log_error_nofargs_capi = cb_log_error_in_mml__user__routines_nofargs;
  if (create_cb_arglist(log_error_capi,log_error_xa_capi,1,0,&cb_log_error_in_mml__user__routines_nofargs,&log_error_args_capi,"failed in processing argument list for call-back log_error.")) {
    jmp_buf log_error_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `log_error`.\n");
    SWAP(log_error_capi,cb_log_error_in_mml__user__routines_capi,PyObject);
    SWAP(log_error_args_capi,cb_log_error_in_mml__user__routines_args_capi,PyTupleObject);
    memcpy(&log_error_jmpbuf,&cb_log_error_in_mml__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable noel */
    f2py_success = int_from_pyobj(&noel,noel_capi,"plastic.umat() 30th argument (noel) can't be converted to int");
  if (f2py_success) {
  /* Processing variable props */
  ;
  capi_props_intent |= F2PY_INTENT_IN;
  capi_props_tmp = array_from_pyobj(NPY_DOUBLE,props_Dims,props_Rank,capi_props_intent,props_capi);
  if (capi_props_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 23rd argument `props' of plastic.umat to C/Fortran array" );
  } else {
    props = (double *)(capi_props_tmp->data);

  /* Processing variable dfgrd1 */
  dfgrd1_Dims[0]=3,dfgrd1_Dims[1]=3;
  capi_dfgrd1_intent |= F2PY_INTENT_IN;
  capi_dfgrd1_tmp = array_from_pyobj(NPY_DOUBLE,dfgrd1_Dims,dfgrd1_Rank,capi_dfgrd1_intent,dfgrd1_capi);
  if (capi_dfgrd1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 29th argument `dfgrd1' of plastic.umat to C/Fortran array" );
  } else {
    dfgrd1 = (double *)(capi_dfgrd1_tmp->data);

  /* Processing variable dfgrd0 */
  dfgrd0_Dims[0]=3,dfgrd0_Dims[1]=3;
  capi_dfgrd0_intent |= F2PY_INTENT_IN;
  capi_dfgrd0_tmp = array_from_pyobj(NPY_DOUBLE,dfgrd0_Dims,dfgrd0_Rank,capi_dfgrd0_intent,dfgrd0_capi);
  if (capi_dfgrd0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 28th argument `dfgrd0' of plastic.umat to C/Fortran array" );
  } else {
    dfgrd0 = (double *)(capi_dfgrd0_tmp->data);

  /* Processing variable pnewdt */
    f2py_success = double_from_pyobj(&pnewdt,pnewdt_capi,"plastic.umat() 26th argument (pnewdt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nshr */
    f2py_success = int_from_pyobj(&nshr,nshr_capi,"plastic.umat() 21st argument (nshr) can't be converted to int");
  if (f2py_success) {
  /* Processing variable drpldt */
    f2py_success = double_from_pyobj(&drpldt,drpldt_capi,"plastic.umat() 10th argument (drpldt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dtime */
    f2py_success = double_from_pyobj(&dtime,dtime_capi,"plastic.umat() 14th argument (dtime) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dtemp */
    f2py_success = double_from_pyobj(&dtemp,dtemp_capi,"plastic.umat() 16th argument (dtemp) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ddsddt */
  ;
  capi_ddsddt_intent |= F2PY_INTENT_INOUT;
  capi_ddsddt_tmp = array_from_pyobj(NPY_DOUBLE,ddsddt_Dims,ddsddt_Rank,capi_ddsddt_intent,ddsddt_capi);
  if (capi_ddsddt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 8th argument `ddsddt' of plastic.umat to C/Fortran array" );
  } else {
    ddsddt = (double *)(capi_ddsddt_tmp->data);

  /* Processing variable sse */
    f2py_success = double_from_pyobj(&sse,sse_capi,"plastic.umat() 4th argument (sse) can't be converted to double");
  if (f2py_success) {
  /* Processing variable npt */
    f2py_success = int_from_pyobj(&npt,npt_capi,"plastic.umat() 31st argument (npt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndi */
    f2py_success = int_from_pyobj(&ndi,ndi_capi,"plastic.umat() 20th argument (ndi) can't be converted to int");
  if (f2py_success) {
  /* Processing variable kinc */
    f2py_success = int_from_pyobj(&kinc,kinc_capi,"plastic.umat() 35th argument (kinc) can't be converted to int");
  if (f2py_success) {
  /* Processing variable temp */
    f2py_success = double_from_pyobj(&temp,temp_capi,"plastic.umat() 15th argument (temp) can't be converted to double");
  if (f2py_success) {
  /* Processing variable kstep */
    f2py_success = int_from_pyobj(&kstep,kstep_capi,"plastic.umat() 34th argument (kstep) can't be converted to int");
  if (f2py_success) {
  /* Processing variable drot */
  drot_Dims[0]=3,drot_Dims[1]=3;
  capi_drot_intent |= F2PY_INTENT_IN;
  capi_drot_tmp = array_from_pyobj(NPY_DOUBLE,drot_Dims,drot_Rank,capi_drot_intent,drot_capi);
  if (capi_drot_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 25th argument `drot' of plastic.umat to C/Fortran array" );
  } else {
    drot = (double *)(capi_drot_tmp->data);

  /* Processing variable nstatv */
    f2py_success = int_from_pyobj(&nstatv,nstatv_capi,"plastic.umat() 22nd argument (nstatv) can't be converted to int");
  if (f2py_success) {
  /* Processing variable coords */
  coords_Dims[0]=3;
  capi_coords_intent |= F2PY_INTENT_IN;
  capi_coords_tmp = array_from_pyobj(NPY_DOUBLE,coords_Dims,coords_Rank,capi_coords_intent,coords_capi);
  if (capi_coords_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 24th argument `coords' of plastic.umat to C/Fortran array" );
  } else {
    coords = (double *)(capi_coords_tmp->data);

  /* Processing variable time */
  time_Dims[0]=2;
  capi_time_intent |= F2PY_INTENT_IN;
  capi_time_tmp = array_from_pyobj(NPY_DOUBLE,time_Dims,time_Rank,capi_time_intent,time_capi);
  if (capi_time_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 13rd argument `time' of plastic.umat to C/Fortran array" );
  } else {
    time = (double *)(capi_time_tmp->data);

  /* Processing variable celent */
    f2py_success = double_from_pyobj(&celent,celent_capi,"plastic.umat() 27th argument (celent) can't be converted to double");
  if (f2py_success) {
  /* Processing variable statev */
  statev_Dims[0]=nstatv;
  capi_statev_intent |= F2PY_INTENT_INOUT;
  capi_statev_tmp = array_from_pyobj(NPY_DOUBLE,statev_Dims,statev_Rank,capi_statev_intent,statev_capi);
  if (capi_statev_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 2nd argument `statev' of plastic.umat to C/Fortran array" );
  } else {
    statev = (double *)(capi_statev_tmp->data);

  /* Processing variable ntens */
  if (ntens_capi == Py_None) ntens = len(ddsddt); else
    f2py_success = int_from_pyobj(&ntens,ntens_capi,"plastic.umat() 1st keyword (ntens) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(ddsddt)>=ntens,"len(ddsddt)>=ntens","1st keyword ntens","umat:ntens=%d",ntens) {
  /* Processing variable ddsdde */
  ddsdde_Dims[0]=ntens,ddsdde_Dims[1]=ntens;
  capi_ddsdde_intent |= F2PY_INTENT_INOUT;
  capi_ddsdde_tmp = array_from_pyobj(NPY_DOUBLE,ddsdde_Dims,ddsdde_Rank,capi_ddsdde_intent,ddsdde_capi);
  if (capi_ddsdde_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 3rd argument `ddsdde' of plastic.umat to C/Fortran array" );
  } else {
    ddsdde = (double *)(capi_ddsdde_tmp->data);

  /* Processing variable drplde */
  drplde_Dims[0]=ntens;
  capi_drplde_intent |= F2PY_INTENT_INOUT;
  capi_drplde_tmp = array_from_pyobj(NPY_DOUBLE,drplde_Dims,drplde_Rank,capi_drplde_intent,drplde_capi);
  if (capi_drplde_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 9th argument `drplde' of plastic.umat to C/Fortran array" );
  } else {
    drplde = (double *)(capi_drplde_tmp->data);

  /* Processing variable stress */
  stress_Dims[0]=ntens;
  capi_stress_intent |= F2PY_INTENT_INOUT;
  capi_stress_tmp = array_from_pyobj(NPY_DOUBLE,stress_Dims,stress_Rank,capi_stress_intent,stress_capi);
  if (capi_stress_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 1st argument `stress' of plastic.umat to C/Fortran array" );
  } else {
    stress = (double *)(capi_stress_tmp->data);

  /* Processing variable nprops */
  if (nprops_capi == Py_None) nprops = len(props); else
    f2py_success = int_from_pyobj(&nprops,nprops_capi,"plastic.umat() 2nd keyword (nprops) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(props)>=nprops,"len(props)>=nprops","2nd keyword nprops","umat:nprops=%d",nprops) {
  /* Processing variable dstran */
  dstran_Dims[0]=ntens;
  capi_dstran_intent |= F2PY_INTENT_IN;
  capi_dstran_tmp = array_from_pyobj(NPY_DOUBLE,dstran_Dims,dstran_Rank,capi_dstran_intent,dstran_capi);
  if (capi_dstran_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 12nd argument `dstran' of plastic.umat to C/Fortran array" );
  } else {
    dstran = (double *)(capi_dstran_tmp->data);

  /* Processing variable stran */
  stran_Dims[0]=ntens;
  capi_stran_intent |= F2PY_INTENT_IN;
  capi_stran_tmp = array_from_pyobj(NPY_DOUBLE,stran_Dims,stran_Rank,capi_stran_intent,stran_capi);
  if (capi_stran_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(plastic_error,"failed in converting 11st argument `stran' of plastic.umat to C/Fortran array" );
  } else {
    stran = (double *)(capi_stran_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_log_message_in_mml__user__routines_jmpbuf)) || (setjmp(cb_log_warning_in_mml__user__routines_jmpbuf)) || (setjmp(cb_log_error_in_mml__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(stress,statev,ddsdde,&sse,&spd,&scd,&rpl,ddsddt,drplde,&drpldt,stran,dstran,time,&dtime,&temp,&dtemp,predef,dpred,cmname,&ndi,&nshr,&ntens,&nstatv,props,&nprops,coords,drot,&pnewdt,&celent,dfgrd0,dfgrd1,&noel,&npt,&layer,&kspt,&kstep,&kinc,slen(cmname));
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_stran_tmp!=stran_capi) {
    Py_XDECREF(capi_stran_tmp); }
  }  /*if (capi_stran_tmp == NULL) ... else of stran*/
  /* End of cleaning variable stran */
  if((PyObject *)capi_dstran_tmp!=dstran_capi) {
    Py_XDECREF(capi_dstran_tmp); }
  }  /*if (capi_dstran_tmp == NULL) ... else of dstran*/
  /* End of cleaning variable dstran */
  } /*CHECKSCALAR(len(props)>=nprops)*/
  } /*if (f2py_success) of nprops*/
  /* End of cleaning variable nprops */
  if((PyObject *)capi_stress_tmp!=stress_capi) {
    Py_XDECREF(capi_stress_tmp); }
  }  /*if (capi_stress_tmp == NULL) ... else of stress*/
  /* End of cleaning variable stress */
  if((PyObject *)capi_drplde_tmp!=drplde_capi) {
    Py_XDECREF(capi_drplde_tmp); }
  }  /*if (capi_drplde_tmp == NULL) ... else of drplde*/
  /* End of cleaning variable drplde */
  if((PyObject *)capi_ddsdde_tmp!=ddsdde_capi) {
    Py_XDECREF(capi_ddsdde_tmp); }
  }  /*if (capi_ddsdde_tmp == NULL) ... else of ddsdde*/
  /* End of cleaning variable ddsdde */
  } /*CHECKSCALAR(len(ddsddt)>=ntens)*/
  } /*if (f2py_success) of ntens*/
  /* End of cleaning variable ntens */
  if((PyObject *)capi_statev_tmp!=statev_capi) {
    Py_XDECREF(capi_statev_tmp); }
  }  /*if (capi_statev_tmp == NULL) ... else of statev*/
  /* End of cleaning variable statev */
  } /*if (f2py_success) of celent*/
  /* End of cleaning variable celent */
  if((PyObject *)capi_time_tmp!=time_capi) {
    Py_XDECREF(capi_time_tmp); }
  }  /*if (capi_time_tmp == NULL) ... else of time*/
  /* End of cleaning variable time */
  if((PyObject *)capi_coords_tmp!=coords_capi) {
    Py_XDECREF(capi_coords_tmp); }
  }  /*if (capi_coords_tmp == NULL) ... else of coords*/
  /* End of cleaning variable coords */
  } /*if (f2py_success) of nstatv*/
  /* End of cleaning variable nstatv */
  if((PyObject *)capi_drot_tmp!=drot_capi) {
    Py_XDECREF(capi_drot_tmp); }
  }  /*if (capi_drot_tmp == NULL) ... else of drot*/
  /* End of cleaning variable drot */
  } /*if (f2py_success) of kstep*/
  /* End of cleaning variable kstep */
  } /*if (f2py_success) of temp*/
  /* End of cleaning variable temp */
  } /*if (f2py_success) of kinc*/
  /* End of cleaning variable kinc */
  } /*if (f2py_success) of ndi*/
  /* End of cleaning variable ndi */
  } /*if (f2py_success) of npt*/
  /* End of cleaning variable npt */
  } /*if (f2py_success) of sse*/
  /* End of cleaning variable sse */
  if((PyObject *)capi_ddsddt_tmp!=ddsddt_capi) {
    Py_XDECREF(capi_ddsddt_tmp); }
  }  /*if (capi_ddsddt_tmp == NULL) ... else of ddsddt*/
  /* End of cleaning variable ddsddt */
  } /*if (f2py_success) of dtemp*/
  /* End of cleaning variable dtemp */
  } /*if (f2py_success) of dtime*/
  /* End of cleaning variable dtime */
  } /*if (f2py_success) of drpldt*/
  /* End of cleaning variable drpldt */
  } /*if (f2py_success) of nshr*/
  /* End of cleaning variable nshr */
  } /*if (f2py_success) of pnewdt*/
  /* End of cleaning variable pnewdt */
  if((PyObject *)capi_dfgrd0_tmp!=dfgrd0_capi) {
    Py_XDECREF(capi_dfgrd0_tmp); }
  }  /*if (capi_dfgrd0_tmp == NULL) ... else of dfgrd0*/
  /* End of cleaning variable dfgrd0 */
  if((PyObject *)capi_dfgrd1_tmp!=dfgrd1_capi) {
    Py_XDECREF(capi_dfgrd1_tmp); }
  }  /*if (capi_dfgrd1_tmp == NULL) ... else of dfgrd1*/
  /* End of cleaning variable dfgrd1 */
  if((PyObject *)capi_props_tmp!=props_capi) {
    Py_XDECREF(capi_props_tmp); }
  }  /*if (capi_props_tmp == NULL) ... else of props*/
  /* End of cleaning variable props */
  } /*if (f2py_success) of noel*/
  /* End of cleaning variable noel */
    CFUNCSMESS("Restoring jmpbuf for `log_error`.\n");
    cb_log_error_in_mml__user__routines_capi = log_error_capi;
    Py_DECREF(cb_log_error_in_mml__user__routines_args_capi);
    cb_log_error_in_mml__user__routines_args_capi = log_error_args_capi;
    cb_log_error_in_mml__user__routines_nofargs = log_error_nofargs_capi;
    memcpy(&cb_log_error_in_mml__user__routines_jmpbuf,&log_error_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable log_error */
  if((PyObject *)capi_predef_tmp!=predef_capi) {
    Py_XDECREF(capi_predef_tmp); }
  }  /*if (capi_predef_tmp == NULL) ... else of predef*/
  /* End of cleaning variable predef */
  if((PyObject *)capi_dpred_tmp!=dpred_capi) {
    Py_XDECREF(capi_dpred_tmp); }
  }  /*if (capi_dpred_tmp == NULL) ... else of dpred*/
  /* End of cleaning variable dpred */
    CFUNCSMESS("Restoring jmpbuf for `log_warning`.\n");
    cb_log_warning_in_mml__user__routines_capi = log_warning_capi;
    Py_DECREF(cb_log_warning_in_mml__user__routines_args_capi);
    cb_log_warning_in_mml__user__routines_args_capi = log_warning_args_capi;
    cb_log_warning_in_mml__user__routines_nofargs = log_warning_nofargs_capi;
    memcpy(&cb_log_warning_in_mml__user__routines_jmpbuf,&log_warning_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable log_warning */
  } /*if (f2py_success) of rpl*/
  /* End of cleaning variable rpl */
  } /*if (f2py_success) of spd*/
  /* End of cleaning variable spd */
    CFUNCSMESS("Restoring jmpbuf for `log_message`.\n");
    cb_log_message_in_mml__user__routines_capi = log_message_capi;
    Py_DECREF(cb_log_message_in_mml__user__routines_args_capi);
    cb_log_message_in_mml__user__routines_args_capi = log_message_args_capi;
    cb_log_message_in_mml__user__routines_nofargs = log_message_nofargs_capi;
    memcpy(&cb_log_message_in_mml__user__routines_jmpbuf,&log_message_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable log_message */
  } /*if (f2py_success) of kspt*/
  /* End of cleaning variable kspt */
    STRINGFREE(cmname);
  }  /*if (f2py_success) of cmname*/
  /* End of cleaning variable cmname */
  } /*if (f2py_success) of scd*/
  /* End of cleaning variable scd */
  } /*if (f2py_success) of layer*/
  /* End of cleaning variable layer */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of umat ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"umat",-1,{{-1}},0,(char *)F_FUNC(umat,UMAT),(f2py_init_func)f2py_rout_plastic_umat,doc_f2py_rout_plastic_umat},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "plastic",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_plastic(void) {
#else
#define RETVAL
PyMODINIT_FUNC initplastic(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = plastic_module = PyModule_Create(&moduledef);
#else
  m = plastic_module = Py_InitModule("plastic", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module plastic (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'plastic' is auto-generated with f2py (version:2).\nFunctions:\n"
"  umat(stress,statev,ddsdde,sse,spd,scd,rpl,ddsddt,drplde,drpldt,stran,dstran,time,dtime,temp,dtemp,predef,dpred,cmname,ndi,nshr,nstatv,props,coords,drot,pnewdt,celent,dfgrd0,dfgrd1,noel,npt,layer,kspt,kstep,kinc,log_message,log_warning,log_error,ntens=len(ddsddt),nprops=len(props),log_message_extra_args=(),log_warning_extra_args=(),log_error_extra_args=())\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  plastic_error = PyErr_NewException ("plastic.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"plastic");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
