
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.2'
version_full = '20966f78951d734f100ed6a6a6feedd15dbe79e7'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

