
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "403d49d7b3ae392ad56728cab62255991850dd91",
 "version": "0.2.post3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
