#!/usr/bin/env python

class Area(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'BackgroundColor': 'Color',
            'FillFormat': 'FillFormat',
            'ForegroundColor': 'Color',
            'Formatting': 'str',
            'InvertIfNegative': 'bool',
            'Transparency': 'float'

        }

        self.attributeMap = {
            'BackgroundColor': 'BackgroundColor','FillFormat': 'FillFormat','ForegroundColor': 'ForegroundColor','Formatting': 'Formatting','InvertIfNegative': 'InvertIfNegative','Transparency': 'Transparency'}       

        self.BackgroundColor = None # Color
        self.FillFormat = None # FillFormat
        self.ForegroundColor = None # Color
        self.Formatting = None # str
        self.InvertIfNegative = None # bool
        self.Transparency = None # float
        
