#!/usr/bin/env python

class AutoFitterOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'AutoFitMergedCells': 'bool',
            'IgnoreHidden': 'bool',
            'OnlyAuto': 'bool'

        }

        self.attributeMap = {
            'AutoFitMergedCells': 'AutoFitMergedCells','IgnoreHidden': 'IgnoreHidden','OnlyAuto': 'OnlyAuto'}       

        self.AutoFitMergedCells = None # bool
        self.IgnoreHidden = None # bool
        self.OnlyAuto = None # bool
        
