#!/usr/bin/env python

class AutoShapesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'AutoShapes': 'AutoShapes',
            'Code': 'str',
            'Status': 'str'

        }

        self.attributeMap = {
            'AutoShapes': 'AutoShapes','Code': 'Code','Status': 'Status'}       

        self.AutoShapes = None # AutoShapes
        self.Code = None # str
        self.Status = None # str
        
