#!/usr/bin/env python

class AutoShape(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'AlternativeText': 'str',
            'Bottom': 'int',
            'Top': 'int',
            'Width': 'int',
            'HtmlText': 'str',
            'TextVerticalAlignment': 'str',
            'AutoShapeType': 'str',
            'IsPrintable': 'bool',
            'UpperLeftColumn': 'int',
            'IsLockAspectRatio': 'bool',
            'IsGroup': 'bool',
            'RotationAngle': 'float',
            'ZOrderPosition': 'int',
            'TextHorizontalOverflow': 'str',
            'TextOrientationType': 'str',
            'Placement': 'str',
            'Name': 'str',
            'IsWordArt': 'bool',
            'LinkedCell': 'str',
            'UpperLeftRow': 'int',
            'IsLocked': 'bool',
            'LowerRightRow': 'int',
            'IsTextWrapped': 'bool',
            'Y': 'int',
            'X': 'int',
            'IsHidden': 'bool',
            'Left': 'int',
            'Right': 'int',
            'Text': 'str',
            'LowerRightColumn': 'int',
            'Height': 'int',
            'TextHorizontalAlignment': 'str',
            'TextVerticalOverflow': 'str',
            'link': 'Link'

        }

        self.attributeMap = {
            'AlternativeText': 'AlternativeText',
            'Bottom': 'Bottom',
            'Top': 'Top',
            'Width': 'Width',
            'HtmlText': 'HtmlText',
            'TextVerticalAlignment': 'TextVerticalAlignment',
            'AutoShapeType': 'AutoShapeType',
            'IsPrintable': 'IsPrintable',
            'UpperLeftColumn': 'UpperLeftColumn',
            'IsLockAspectRatio': 'IsLockAspectRatio',
            'IsGroup': 'IsGroup',
            'RotationAngle': 'RotationAngle',
            'ZOrderPosition': 'ZOrderPosition',
            'TextHorizontalOverflow': 'TextHorizontalOverflow',
            'TextOrientationType': 'TextOrientationType',
            'Placement': 'Placement',
            'Name': 'Name',
            'IsWordArt': 'IsWordArt',
            'LinkedCell': 'LinkedCell',
            'UpperLeftRow': 'UpperLeftRow',
            'IsLocked': 'IsLocked',
            'LowerRightRow': 'LowerRightRow',
            'IsTextWrapped': 'IsTextWrapped',
            'Y': 'Y',
            'X': 'X',
            'IsHidden': 'IsHidden',
            'Left': 'Left',
            'Right': 'Right',
            'Text': 'Text',
            'LowerRightColumn': 'LowerRightColumn',
            'Height': 'Height',
            'TextHorizontalAlignment': 'TextHorizontalAlignment',
            'TextVerticalOverflow': 'TextVerticalOverflow',
            'link': 'link'}       

        self.AlternativeText = None # str
        self.Bottom = None # int
        self.Top = None # int
        self.Width = None # int
        self.HtmlText = None # str
        self.TextVerticalAlignment = None # str
        self.AutoShapeType = None # str
        self.IsPrintable = None # bool
        self.UpperLeftColumn = None # int
        self.IsLockAspectRatio = None # bool
        self.IsGroup = None # bool
        self.RotationAngle = None # float
        self.ZOrderPosition = None # int
        self.TextHorizontalOverflow = None # str
        self.TextOrientationType = None # str
        self.Placement = None # str
        self.Name = None # str
        self.IsWordArt = None # bool
        self.LinkedCell = None # str
        self.UpperLeftRow = None # int
        self.IsLocked = None # bool
        self.LowerRightRow = None # int
        self.IsTextWrapped = None # bool
        self.Y = None # int
        self.X = None # int
        self.IsHidden = None # bool
        self.Left = None # int
        self.Right = None # int
        self.Text = None # str
        self.LowerRightColumn = None # int
        self.Height = None # int
        self.TextHorizontalAlignment = None # str
        self.TextVerticalOverflow = None # str        
        self.link = None # Link
        
