#!/usr/bin/env python

class CellsColor(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Color': 'Color',
            'ColorIndex': 'int',
            'IsShapeColor': 'bool',
            'ThemeColor': 'ThemeColor',
            'Type': 'str'

        }

        self.attributeMap = {
            'Color': 'Color','ColorIndex': 'ColorIndex','IsShapeColor': 'IsShapeColor','ThemeColor': 'ThemeColor','Type': 'Type'}       

        self.Color = None # Color
        self.ColorIndex = None # int
        self.IsShapeColor = None # bool
        self.ThemeColor = None # ThemeColor
        self.Type = None # str
        
