#!/usr/bin/env python

class DataSorter(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'CaseSensitive': 'str',
            'HasHeaders': 'str',
            'KeyList': 'list[SortKey]',
            'SortLeftToRight': 'str'

        }

        self.attributeMap = {
            'CaseSensitive': 'CaseSensitive','HasHeaders': 'HasHeaders','KeyList': 'KeyList','SortLeftToRight': 'SortLeftToRight'}       

        self.CaseSensitive = None # str
        self.HasHeaders = None # str
        self.KeyList = None # list[SortKey]
        self.SortLeftToRight = None # str
        
