#!/usr/bin/env python

class DynamicFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'DynamicFilterType': 'str',
            'MaxValue': 'object',
            'Value': 'object'

        }

        self.attributeMap = {
            'DynamicFilterType': 'DynamicFilterType','MaxValue': 'MaxValue','Value': 'Value'}       

        self.DynamicFilterType = None # str
        self.MaxValue = None # object
        self.Value = None # object
        
