#!/usr/bin/env python

class GradientFillStop(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Color': 'Color',
            'Position': 'float',
            'Transparency': 'float'

        }

        self.attributeMap = {
            'Color': 'Color','Position': 'Position','Transparency': 'Transparency'}       

        self.Color = None # Color
        self.Position = None # float
        self.Transparency = None # float
        
