#!/usr/bin/env python

class IconFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'IconId': 'int',
            'IconSetType': 'str'

        }

        self.attributeMap = {
            'IconId': 'IconId','IconSetType': 'IconSetType'}       

        self.IconId = None # int
        self.IconSetType = None # str
        
