#!/usr/bin/env python

class ImportOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'DestinationWorksheet': 'str',
            'IsInsert': 'bool'

        }

        self.attributeMap = {
            'DestinationWorksheet': 'DestinationWorksheet','IsInsert': 'IsInsert'}       

        self.DestinationWorksheet = None # str
        self.IsInsert = None # bool
        
