#!/usr/bin/env python

class Line(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'BeginArrowLength': 'str',
            'BeginArrowWidth': 'str',
            'BeginType': 'str',
            'CapType': 'str',
            'Color': 'Color',
            'CompoundType': 'str',
            'DashType': 'str',
            'EndArrowLength': 'str',
            'EndArrowWidth': 'str',
            'EndType': 'str',
            'GradientFill': 'GradientFill',
            'IsAuto': 'bool',
            'IsAutomaticColor': 'bool',
            'IsVisible': 'bool',
            'JoinType': 'str',
            'Style': 'str',
            'Transparency': 'float',
            'Weight': 'str',
            'WeightPt': 'float'

        }

        self.attributeMap = {
            'BeginArrowLength': 'BeginArrowLength','BeginArrowWidth': 'BeginArrowWidth','BeginType': 'BeginType','CapType': 'CapType','Color': 'Color','CompoundType': 'CompoundType','DashType': 'DashType','EndArrowLength': 'EndArrowLength','EndArrowWidth': 'EndArrowWidth','EndType': 'EndType','GradientFill': 'GradientFill','IsAuto': 'IsAuto','IsAutomaticColor': 'IsAutomaticColor','IsVisible': 'IsVisible','JoinType': 'JoinType','Style': 'Style','Transparency': 'Transparency','Weight': 'Weight','WeightPt': 'WeightPt'}       

        self.BeginArrowLength = None # str
        self.BeginArrowWidth = None # str
        self.BeginType = None # str
        self.CapType = None # str
        self.Color = None # Color
        self.CompoundType = None # str
        self.DashType = None # str
        self.EndArrowLength = None # str
        self.EndArrowWidth = None # str
        self.EndType = None # str
        self.GradientFill = None # GradientFill
        self.IsAuto = None # bool
        self.IsAutomaticColor = None # bool
        self.IsVisible = None # bool
        self.JoinType = None # str
        self.Style = None # str
        self.Transparency = None # float
        self.Weight = None # str
        self.WeightPt = None # float
        
