#!/usr/bin/env python

class MergedCell(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'EndColumn': 'int',
            'EndRow': 'int',
            'StartColumn': 'int',
            'StartRow': 'int',
            'link': 'Link'

        }

        self.attributeMap = {
            'EndColumn': 'EndColumn','EndRow': 'EndRow','StartColumn': 'StartColumn','StartRow': 'StartRow','link': 'link'}       

        self.EndColumn = None # int
        self.EndRow = None # int
        self.StartColumn = None # int
        self.StartRow = None # int
        self.link = None # Link
        
