#!/usr/bin/env python

class OleObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'DisplayAsIcon': 'bool',
            'FileFormatType': 'str',
            'ImageSourceFullName': 'str',
            'IsAutoSize': 'bool',
            'IsLink': 'bool',
            'ProgID': 'str',
            'SourceFullName': 'str',
            'Name': 'str',
            'MsoDrawingType': 'str',
            'AutoShapeType': 'str',
            'Placement': 'str',
            'UpperLeftRow': 'int',
            'Top': 'int',
            'UpperLeftColumn': 'int',
            'Left': 'int',
            'LowerRightRow': 'int',
            'Bottom': 'int',
            'LowerRightColumn': 'int',
            'Right': 'int',
            'Width': 'int',
            'Height': 'int',
            'X': 'int',
            'Y': 'int',
            'RotationAngle': 'float',
            'HtmlText': 'str',
            'Text': 'str',
            'AlternativeText': 'str',
            'TextHorizontalAlignment': 'str',
            'TextHorizontalOverflow': 'str',
            'TextOrientationType': 'str',
            'TextVerticalAlignment': 'str',
            'TextVerticalOverflow': 'str',
            'IsGroup': 'bool',
            'IsHidden': 'bool',
            'IsLockAspectRatio': 'bool',
            'IsLocked': 'bool',
            'IsPrintable': 'bool',
            'IsTextWrapped': 'bool',
            'IsWordArt': 'bool',
            'LinkedCell': 'str',
            'ZOrderPosition': 'int',
            'link': 'Link'

        }

        self.attributeMap = {
            'DisplayAsIcon': 'DisplayAsIcon','FileFormatType': 'FileFormatType','ImageSourceFullName': 'ImageSourceFullName','IsAutoSize': 'IsAutoSize','IsLink': 'IsLink','ProgID': 'ProgID','SourceFullName': 'SourceFullName','Name': 'Name','MsoDrawingType': 'MsoDrawingType','AutoShapeType': 'AutoShapeType','Placement': 'Placement','UpperLeftRow': 'UpperLeftRow','Top': 'Top','UpperLeftColumn': 'UpperLeftColumn','Left': 'Left','LowerRightRow': 'LowerRightRow','Bottom': 'Bottom','LowerRightColumn': 'LowerRightColumn','Right': 'Right','Width': 'Width','Height': 'Height','X': 'X','Y': 'Y','RotationAngle': 'RotationAngle','HtmlText': 'HtmlText','Text': 'Text','AlternativeText': 'AlternativeText','TextHorizontalAlignment': 'TextHorizontalAlignment','TextHorizontalOverflow': 'TextHorizontalOverflow','TextOrientationType': 'TextOrientationType','TextVerticalAlignment': 'TextVerticalAlignment','TextVerticalOverflow': 'TextVerticalOverflow','IsGroup': 'IsGroup','IsHidden': 'IsHidden','IsLockAspectRatio': 'IsLockAspectRatio','IsLocked': 'IsLocked','IsPrintable': 'IsPrintable','IsTextWrapped': 'IsTextWrapped','IsWordArt': 'IsWordArt','LinkedCell': 'LinkedCell','ZOrderPosition': 'ZOrderPosition','link': 'link'}       

        self.DisplayAsIcon = None # bool
        self.FileFormatType = None # str
        self.ImageSourceFullName = None # str
        self.IsAutoSize = None # bool
        self.IsLink = None # bool
        self.ProgID = None # str
        self.SourceFullName = None # str
        self.Name = None # str
        self.MsoDrawingType = None # str
        self.AutoShapeType = None # str
        self.Placement = None # str
        self.UpperLeftRow = None # int
        self.Top = None # int
        self.UpperLeftColumn = None # int
        self.Left = None # int
        self.LowerRightRow = None # int
        self.Bottom = None # int
        self.LowerRightColumn = None # int
        self.Right = None # int
        self.Width = None # int
        self.Height = None # int
        self.X = None # int
        self.Y = None # int
        self.RotationAngle = None # float
        self.HtmlText = None # str
        self.Text = None # str
        self.AlternativeText = None # str
        self.TextHorizontalAlignment = None # str
        self.TextHorizontalOverflow = None # str
        self.TextOrientationType = None # str
        self.TextVerticalAlignment = None # str
        self.TextVerticalOverflow = None # str
        self.IsGroup = None # bool
        self.IsHidden = None # bool
        self.IsLockAspectRatio = None # bool
        self.IsLocked = None # bool
        self.IsPrintable = None # bool
        self.IsTextWrapped = None # bool
        self.IsWordArt = None # bool
        self.LinkedCell = None # str
        self.ZOrderPosition = None # int
        self.link = None # Link
        
