#!/usr/bin/env python

class PasswordRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Password': 'str'

        }

        self.attributeMap = {
            'Password': 'Password'}       

        self.Password = None # str
        
