#!/usr/bin/env python

class Pictures(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'PictureList': 'list[LinkElement]',
            'link': 'Link'

        }

        self.attributeMap = {
            'PictureList': 'PictureList','link': 'link'}       

        self.PictureList = None # list[LinkElement]
        self.link = None # Link
        
