#!/usr/bin/env python

class PivotItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Index': 'int',
            'IsHidden': 'bool',
            'Name': 'str',
            'Value': 'str'

        }

        self.attributeMap = {
            'Index': 'Index','IsHidden': 'IsHidden','Name': 'Name','Value': 'Value'}       

        self.Index = None # int
        self.IsHidden = None # bool
        self.Name = None # str
        self.Value = None # object
        
