#!/usr/bin/env python

class Style(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Font': 'Font',
            'Name': 'str',
            'CultureCustom': 'str',
            'Custom': 'str',
            'BackgroundColor': 'Color',
            'ForegroundColor': 'Color',
            'IsFormulaHidden': 'bool',
            'IsDateTime': 'bool',
            'IsTextWrapped': 'bool',
            'IsGradient': 'bool',
            'IsLocked': 'bool',
            'IsPercent': 'bool',
            'ShrinkToFit': 'bool',
            'IndentLevel': 'int',
            'Number': 'int',
            'RotationAngle': 'int',
            'Pattern': 'str',
            'TextDirection': 'str',
            'VerticalAlignment': 'str',
            'HorizontalAlignment': 'str',
            'BorderCollection': 'list[Border]',
            'link': 'Link'

        }

        self.attributeMap = {
            'Font': 'Font','Name': 'Name','CultureCustom': 'CultureCustom','Custom': 'Custom','BackgroundColor': 'BackgroundColor','ForegroundColor': 'ForegroundColor','IsFormulaHidden': 'IsFormulaHidden','IsDateTime': 'IsDateTime','IsTextWrapped': 'IsTextWrapped','IsGradient': 'IsGradient','IsLocked': 'IsLocked','IsPercent': 'IsPercent','ShrinkToFit': 'ShrinkToFit','IndentLevel': 'IndentLevel','Number': 'Number','RotationAngle': 'RotationAngle','Pattern': 'Pattern','TextDirection': 'TextDirection','VerticalAlignment': 'VerticalAlignment','HorizontalAlignment': 'HorizontalAlignment','BorderCollection': 'BorderCollection','link': 'link'}       

        self.Font = None # Font
        self.Name = None # str
        self.CultureCustom = None # str
        self.Custom = None # str
        self.BackgroundColor = None # Color
        self.ForegroundColor = None # Color
        self.IsFormulaHidden = None # bool
        self.IsDateTime = None # bool
        self.IsTextWrapped = None # bool
        self.IsGradient = None # bool
        self.IsLocked = None # bool
        self.IsPercent = None # bool
        self.ShrinkToFit = None # bool
        self.IndentLevel = None # int
        self.Number = None # int
        self.RotationAngle = None # int
        self.Pattern = None # str
        self.TextDirection = None # str
        self.VerticalAlignment = None # str
        self.HorizontalAlignment = None # str
        self.BorderCollection = None # list[Border]
        self.link = None # Link
        
