#!/usr/bin/env python

class TextureFill(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Type': 'str',
            'Transparency': 'float',
            'Scale': 'float',
            'TilePicOption': 'TilePicOption',
            'PicFormatOption': 'PicFormatOption',
            'Image': 'LinkElement'

        }

        self.attributeMap = {
            'Type': 'Type','Transparency': 'Transparency','Scale': 'Scale','TilePicOption': 'TilePicOption','PicFormatOption': 'PicFormatOption','Image': 'Image'}       

        self.Type = None # str
        self.Transparency = None # float
        self.Scale = None # float
        self.TilePicOption = None # TilePicOption
        self.PicFormatOption = None # PicFormatOption
        self.Image = None # LinkElement
        
