#!/usr/bin/env python

class TilePicOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'OffsetX': 'float',
            'OffsetY': 'float',
            'ScaleX': 'float',
            'ScaleY': 'float',
            'AlignmentType': 'str',
            'MirrorType': 'str'

        }

        self.attributeMap = {
            'OffsetX': 'OffsetX','OffsetY': 'OffsetY','ScaleX': 'ScaleX','ScaleY': 'ScaleY','AlignmentType': 'AlignmentType','MirrorType': 'MirrorType'}       

        self.OffsetX = None # float
        self.OffsetY = None # float
        self.ScaleX = None # float
        self.ScaleY = None # float
        self.AlignmentType = None # str
        self.MirrorType = None # str
        
