#!/usr/bin/env python

class Title(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'IsVisible': 'bool',
            'LinkedSource': 'str',
            'RotationAngle': 'int',
            'Text': 'str',
            'TextDirection': 'str',
            'TextHorizontalAlignment': 'str',
            'TextVerticalAlignment': 'str',
            'Area': 'Area',
            'AutoScaleFont': 'bool',
            'BackgroundMode': 'str',
            'Border': 'Line',
            'Font': 'Font',
            'IsAutomaticSize': 'bool',
            'IsInnerMode': 'bool',
            'Shadow': 'bool',
            'ShapeProperties': 'list[LinkElement]',
            'Width': 'int',
            'Height': 'int',
            'X': 'int',
            'Y': 'int',
            'link': 'Link'

        }

        self.attributeMap = {
            'IsVisible': 'IsVisible','LinkedSource': 'LinkedSource','RotationAngle': 'RotationAngle','Text': 'Text','TextDirection': 'TextDirection','TextHorizontalAlignment': 'TextHorizontalAlignment','TextVerticalAlignment': 'TextVerticalAlignment','Area': 'Area','AutoScaleFont': 'AutoScaleFont','BackgroundMode': 'BackgroundMode','Border': 'Border','Font': 'Font','IsAutomaticSize': 'IsAutomaticSize','IsInnerMode': 'IsInnerMode','Shadow': 'Shadow','ShapeProperties': 'ShapeProperties','Width': 'Width','Height': 'Height','X': 'X','Y': 'Y','link': 'link'}       

        self.IsVisible = None # bool
        self.LinkedSource = None # str
        self.RotationAngle = None # int
        self.Text = None # str
        self.TextDirection = None # str
        self.TextHorizontalAlignment = None # str
        self.TextVerticalAlignment = None # str
        self.Area = None # Area
        self.AutoScaleFont = None # bool
        self.BackgroundMode = None # str
        self.Border = None # Line
        self.Font = None # Font
        self.IsAutomaticSize = None # bool
        self.IsInnerMode = None # bool
        self.Shadow = None # bool
        self.ShapeProperties = None # list[LinkElement]
        self.Width = None # int
        self.Height = None # int
        self.X = None # int
        self.Y = None # int
        self.link = None # Link
        
