#!/usr/bin/env python

class Validation(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'AlertStyle': 'str',
            'AreaList': 'list[CellArea]',
            'ErrorMessage': 'str',
            'ErrorTitle': 'str',
            'Formula1': 'str',
            'Formula2': 'str',
            'IgnoreBlank': 'bool',
            'InCellDropDown': 'bool',
            'InputMessage': 'str',
            'InputTitle': 'str',
            'Operator': 'str',
            'ShowError': 'bool',
            'ShowInput': 'bool',
            'Type': 'str',
            'Value1': 'str',
            'Value2': 'str',
            'link': 'Link'

        }

        self.attributeMap = {
            'AlertStyle': 'AlertStyle','AreaList': 'AreaList','ErrorMessage': 'ErrorMessage','ErrorTitle': 'ErrorTitle','Formula1': 'Formula1','Formula2': 'Formula2','IgnoreBlank': 'IgnoreBlank','InCellDropDown': 'InCellDropDown','InputMessage': 'InputMessage','InputTitle': 'InputTitle','Operator': 'Operator','ShowError': 'ShowError','ShowInput': 'ShowInput','Type': 'Type','Value1': 'Value1','Value2': 'Value2','link': 'link'}       

        self.AlertStyle = None # str
        self.AreaList = None # list[CellArea]
        self.ErrorMessage = None # str
        self.ErrorTitle = None # str
        self.Formula1 = None # str
        self.Formula2 = None # str
        self.IgnoreBlank = None # bool
        self.InCellDropDown = None # bool
        self.InputMessage = None # str
        self.InputTitle = None # str
        self.Operator = None # str
        self.ShowError = None # bool
        self.ShowInput = None # bool
        self.Type = None # str
        self.Value1 = None # str
        self.Value2 = None # str
        self.link = None # Link
        
