#!/usr/bin/env python

class Version(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {                             
            '_Major':'int',
            '_Revision':'int',
            '_Minor':'int',
            '_Build':'int'
            }

        self.attributeMap = {
                             '_Major':'_Major','_Revision':'_Revision','_Minor':'_Minor','_Build':'_Build'
            }       

        self._Major = None
        self._Revision = None
        self._Minor = None
        self._Build = None
        
