#!/usr/bin/env python

class WorkbookEncryptionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'EncryptionType': 'str',
            'KeyLength': 'int',
            'Password': 'str'

        }

        self.attributeMap = {
            'EncryptionType': 'EncryptionType','KeyLength': 'KeyLength','Password': 'Password'}       

        self.EncryptionType = None # str
        self.KeyLength = None # int
        self.Password = None # str
        
