
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "fdccfe1dc0e17b2c0c7a89de9c4e73975023accd",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
